/* ============================================================
   PokéTactics – Spieldaten
   Typen, Attacken, Spezies, Sprites, Schlachten
   ============================================================ */
"use strict";

/* ---------- Typen ---------- */
const TYPES = {
  normal:   { name: "Normal",   color: "#9ca3af" },
  fire:     { name: "Feuer",    color: "#f97316" },
  water:    { name: "Wasser",   color: "#3b82f6" },
  grass:    { name: "Pflanze",  color: "#22c55e" },
  electric: { name: "Elektro",  color: "#eab308" },
  psychic:  { name: "Psycho",   color: "#ec4899" },
  fighting: { name: "Kampf",    color: "#b91c1c" },
  rock:     { name: "Gestein",  color: "#a16207" },
  ground:   { name: "Boden",    color: "#d97706" },
  flying:   { name: "Flug",     color: "#818cf8" },
  poison:   { name: "Gift",     color: "#a855f7" },
  ghost:    { name: "Geist",    color: "#6d28d9" },
};

/* Angriffstyp -> { Verteidigertyp: Multiplikator }, fehlend = 1 */
const TYPE_CHART = {
  normal:   { rock: .5, ghost: 0 },
  fire:     { grass: 2, water: .5, fire: .5, rock: .5 },
  water:    { fire: 2, rock: 2, ground: 2, water: .5, grass: .5 },
  grass:    { water: 2, rock: 2, ground: 2, fire: .5, grass: .5, flying: .5, poison: .5 },
  electric: { water: 2, flying: 2, grass: .5, electric: .5, ground: 0 },
  psychic:  { fighting: 2, poison: 2, psychic: .5 },
  fighting: { normal: 2, rock: 2, flying: .5, psychic: .5, poison: .5, ghost: 0 },
  rock:     { fire: 2, flying: 2, fighting: .5, ground: .5 },
  ground:   { fire: 2, electric: 2, rock: 2, poison: 2, grass: .5, flying: 0 },
  flying:   { grass: 2, fighting: 2, electric: .5, rock: .5 },
  poison:   { grass: 2, poison: .5, ground: .5, rock: .5, ghost: .5 },
  ghost:    { ghost: 2, psychic: 2, normal: 0 },
};

function typeMult(atkType, defTypes) {
  let m = 1;
  for (const dt of defTypes) {
    const row = TYPE_CHART[atkType];
    if (row && row[dt] !== undefined) m *= row[dt];
  }
  return m;
}

/* ---------- Status ---------- */
const STATUS = {
  brn: { name: "Brand",    icon: "🔥", color: "#fdba74" },
  psn: { name: "Gift",     icon: "☠",  color: "#d8b4fe" },
  par: { name: "Paralyse", icon: "⚡", color: "#fde047" },
  slp: { name: "Schlaf",   icon: "💤", color: "#93c5fd" },
};

/* ---------- Attacken ----------
   cat: 'p' physisch, 'm' speziell, 's' status
   rng: Reichweite (0 = selbst/Umkreis), aoe: 0 einzeln, 1 Kreuz, 2 Umkreis
   target: foe | ally | self
*/
const MOVES = {
  hieb:        { name: "Hieb",        type: "normal",  cat: "p", pow: 35, rng: 1, aoe: 0, acc: 95, pp: Infinity, target: "foe", desc: "Einfacher Nahkampfangriff." },

  tackle:      { name: "Tackle",      type: "normal",  cat: "p", pow: 45, rng: 1, aoe: 0, acc: 95, pp: 20, target: "foe", desc: "Rammt das Ziel mit vollem Körpereinsatz." },
  ruckzuck:    { name: "Ruckzuckhieb",type: "normal",  cat: "p", pow: 40, rng: 2, aoe: 0, acc: 100, pp: 12, target: "foe", desc: "Blitzschneller Sturmangriff über 2 Felder." },
  bodyslam:    { name: "Bodyslam",    type: "normal",  cat: "p", pow: 70, rng: 1, aoe: 0, acc: 90, pp: 8, fx: { st: "par", ch: 30 }, target: "foe", desc: "Schwerer Wurf, kann paralysieren." },
  sternschauer:{ name: "Sternschauer",type: "normal",  cat: "m", pow: 55, rng: 3, aoe: 0, acc: 999, pp: 10, target: "foe", desc: "Sterne, die niemals verfehlen." },
  heuler:      { name: "Heuler",      type: "normal",  cat: "s", pow: 0,  rng: 2, aoe: 1, acc: 100, pp: 8, buff: { stat: "atk", mult: .7, dur: 3 }, target: "foe", desc: "Senkt den Angriff der Gegner im Umkreis." },
  erholung:    { name: "Erholung",    type: "normal",  cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 3, heal: 1, fx: { st: "slp", ch: 100, self: true }, target: "self", desc: "Heilt vollständig, aber schläfert selbst ein." },

  donnerschock:{ name: "Donnerschock",type: "electric",cat: "m", pow: 50, rng: 3, aoe: 0, acc: 95, pp: 15, fx: { st: "par", ch: 10 }, target: "foe", desc: "Elektroschock auf Distanz." },
  donnerblitz: { name: "Donnerblitz", type: "electric",cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, fx: { st: "par", ch: 15 }, target: "foe", desc: "Mächtiger Blitzschlag, kann paralysieren." },
  donnerwelle: { name: "Donnerwelle", type: "electric",cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 85, pp: 8, fx: { st: "par", ch: 100 }, target: "foe", desc: "Paralysiert das Ziel zuverlässig." },
  funkensprung:{ name: "Funkensprung",type: "electric",cat: "m", pow: 60, rng: 2, aoe: 1, acc: 90, pp: 6, target: "foe", desc: "Entlädt Funken im Kreuzbereich." },

  glut:        { name: "Glut",        type: "fire",    cat: "m", pow: 50, rng: 2, aoe: 0, acc: 95, pp: 15, fx: { st: "brn", ch: 15 }, target: "foe", desc: "Kleine Flamme, kann Brand verursachen." },
  flammenwurf: { name: "Flammenwurf", type: "fire",    cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, fx: { st: "brn", ch: 20 }, target: "foe", desc: "Heißer Flammenstrahl." },
  feuerwirbel: { name: "Feuerwirbel", type: "fire",    cat: "m", pow: 55, rng: 2, aoe: 1, acc: 90, pp: 6, fx: { st: "brn", ch: 15 }, target: "foe", desc: "Flammen im Kreuzbereich." },

  aquaknarre:  { name: "Aquaknarre",  type: "water",   cat: "m", pow: 50, rng: 3, aoe: 0, acc: 95, pp: 15, target: "foe", desc: "Gezielter Wasserstrahl." },
  blubbstrahl: { name: "Blubbstrahl", type: "water",   cat: "m", pow: 65, rng: 3, aoe: 0, acc: 95, pp: 10, buff: { stat: "spd", mult: .75, dur: 2 }, target: "foe", desc: "Blasen, die das Ziel verlangsamen." },
  hydropumpe:  { name: "Hydropumpe",  type: "water",   cat: "m", pow: 90, rng: 3, aoe: 0, acc: 80, pp: 5, target: "foe", desc: "Gewaltige Wasserkanone." },
  panzerschutz:{ name: "Panzerschutz",type: "water",   cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 6, buff: { stat: "def", mult: 1.5, dur: 3 }, target: "self", desc: "Erhöht die eigene Verteidigung stark." },

  rankenhieb:  { name: "Rankenhieb",  type: "grass",   cat: "p", pow: 50, rng: 2, aoe: 0, acc: 100, pp: 15, target: "foe", desc: "Peitscht mit Ranken über 2 Felder." },
  rasierblatt: { name: "Rasierblatt", type: "grass",   cat: "p", pow: 60, rng: 3, aoe: 1, acc: 90, pp: 8, target: "foe", desc: "Blätterhagel im Kreuzbereich." },
  megasauger:  { name: "Megasauger",  type: "grass",   cat: "m", pow: 45, rng: 2, aoe: 0, acc: 100, pp: 10, drain: .6, target: "foe", desc: "Saugt KP ab und heilt sich selbst." },
  schlafpuder: { name: "Schlafpuder", type: "grass",   cat: "s", pow: 0,  rng: 2, aoe: 0, acc: 70, pp: 6, fx: { st: "slp", ch: 100 }, target: "foe", desc: "Schläfert das Ziel ein." },

  konfusion:   { name: "Konfusion",   type: "psychic", cat: "m", pow: 55, rng: 3, aoe: 0, acc: 95, pp: 15, target: "foe", desc: "Telekinetischer Stoß." },
  psystrahl:   { name: "Psystrahl",   type: "psychic", cat: "m", pow: 70, rng: 3, aoe: 0, acc: 95, pp: 8, target: "foe", desc: "Schillernder Psycho-Strahl." },
  psychokinese:{ name: "Psychokinese",type: "psychic", cat: "m", pow: 78, rng: 3, aoe: 1, acc: 90, pp: 5, target: "foe", desc: "Gewaltige Psycho-Druckwelle." },
  genesung:    { name: "Genesung",    type: "psychic", cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 5, heal: .5, target: "self", desc: "Heilt die Hälfte der eigenen max. KP." },
  barriere:    { name: "Barriere",    type: "psychic", cat: "s", pow: 0,  rng: 2, aoe: 0, acc: 100, pp: 6, buff: { stat: "def", mult: 1.4, dur: 3 }, target: "ally", desc: "Schützt einen Verbündeten." },
  hypnose:     { name: "Hypnose",     type: "psychic", cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 65, pp: 6, fx: { st: "slp", ch: 100 }, target: "foe", desc: "Hypnotisiert das Ziel in den Schlaf." },

  karateschlag:{ name: "Karateschlag",type: "fighting",cat: "p", pow: 55, rng: 1, aoe: 0, acc: 95, pp: 15, crit: 15, target: "foe", desc: "Präziser Schlag, oft Volltreffer." },
  geowurf:     { name: "Geowurf",     type: "fighting",cat: "p", pow: 70, rng: 1, aoe: 0, acc: 90, pp: 8, target: "foe", desc: "Schleudert das Ziel zu Boden." },
  protzer:     { name: "Protzer",     type: "fighting",cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 6, buff: { stat: "atk", mult: 1.4, dur: 3 }, target: "self", desc: "Pumpt sich auf: Angriff steigt." },

  schlecker:   { name: "Schlecker",   type: "ghost",   cat: "p", pow: 35, rng: 1, aoe: 0, acc: 100, pp: 15, fx: { st: "par", ch: 30 }, target: "foe", desc: "Eklige Zunge, kann paralysieren." },
  nachtnebel:  { name: "Nachtnebel",  type: "ghost",   cat: "m", pow: 55, rng: 3, aoe: 0, acc: 95, pp: 12, target: "foe", desc: "Unheimlicher Schattenstoß." },
  spukball:    { name: "Spukball",    type: "ghost",   cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, target: "foe", desc: "Geballte Schattenenergie." },

  steinwurf:   { name: "Steinwurf",   type: "rock",    cat: "p", pow: 55, rng: 3, aoe: 0, acc: 90, pp: 12, target: "foe", desc: "Wirft einen Felsbrocken." },
  steinhagel:  { name: "Steinhagel",  type: "rock",    cat: "p", pow: 65, rng: 3, aoe: 1, acc: 85, pp: 6, target: "foe", desc: "Steinschlag im Kreuzbereich." },
  haertner:    { name: "Härtner",     type: "rock",    cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 8, buff: { stat: "def", mult: 1.4, dur: 3 }, target: "self", desc: "Verhärtet den Körper." },

  knochenkeule:{ name: "Knochenkeule",type: "ground",  cat: "p", pow: 60, rng: 1, aoe: 0, acc: 95, pp: 12, target: "foe", desc: "Schlag mit der Knochenkeule." },
  knochmerang: { name: "Knochmerang", type: "ground",  cat: "p", pow: 55, rng: 3, aoe: 0, acc: 90, pp: 8, target: "foe", desc: "Geworfener Knochen-Bumerang." },
  intensitaet: { name: "Intensität",  type: "ground",  cat: "p", pow: 60, rng: 0, aoe: 2, acc: 95, pp: 6, target: "foe", desc: "Erdbeben rund um den Anwender." },
  schaufler:   { name: "Schaufler",   type: "ground",  cat: "p", pow: 65, rng: 2, aoe: 0, acc: 95, pp: 8, target: "foe", desc: "Angriff aus dem Untergrund." },

  windstoss:   { name: "Windstoß",    type: "flying",  cat: "m", pow: 45, rng: 3, aoe: 0, acc: 95, pp: 15, target: "foe", desc: "Schneidende Windböe." },
  fluegelschlag:{ name:"Flügelschlag",type: "flying",  cat: "p", pow: 60, rng: 2, aoe: 0, acc: 95, pp: 10, target: "foe", desc: "Schlag mit harten Schwingen." },
  schnabel:    { name: "Schnabel",    type: "flying",  cat: "p", pow: 45, rng: 1, aoe: 0, acc: 100, pp: 15, target: "foe", desc: "Pickt mit spitzem Schnabel." },

  giftstachel: { name: "Giftstachel", type: "poison",  cat: "p", pow: 40, rng: 2, aoe: 0, acc: 95, pp: 15, fx: { st: "psn", ch: 30 }, target: "foe", desc: "Giftiger Stich." },
  saeure:      { name: "Säure",       type: "poison",  cat: "m", pow: 50, rng: 2, aoe: 1, acc: 90, pp: 8, fx: { st: "psn", ch: 20 }, target: "foe", desc: "Ätzende Säure im Kreuzbereich." },
  biss:        { name: "Biss",        type: "normal",  cat: "p", pow: 55, rng: 1, aoe: 0, acc: 95, pp: 12, target: "foe", desc: "Kräftiger Biss." },
  superschall: { name: "Superschall", type: "flying",  cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 75, pp: 8, buff: { stat: "atk", mult: .65, dur: 3 }, target: "foe", desc: "Schrille Wellen schwächen den Angriff." },

  heilwoge:    { name: "Heilwoge",    type: "psychic", cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 100, pp: 8, heal: .45, target: "ally", desc: "Heilt einen Verbündeten (45 % max. KP)." },
  psychoklinge:{ name: "Psychoklinge",type: "psychic", cat: "m", pow: 72, rng: 4, aoe: 1, acc: 95, pp: 6, target: "foe", desc: "Mewtus verheerende Psycho-Klinge." },
};

/* ---------- Spezies ----------
   base: [KP, ANG, VER, TEMPO], grow: Zuwachs pro Level
   mov: Bewegung, jmp: Sprunghöhe, fly: schwebt, swim: darf ins Wasser
*/
const SPECIES = {
  /* === Spieler-Pokémon === */
  pikachu: {
    dex: 25, name: "Pikachu", role: "Blitzmagier", types: ["electric"], sprite: "pikachu",
    base: [38, 16, 12, 11], grow: [3.6, 1.7, 1.3, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"donnerschock"],[4,"donnerwelle"],[7,"funkensprung"],[10,"donnerblitz"]],
    evoLvl: 12, evoTo: "raichu",
  },
  raichu: {
    dex: 26, name: "Raichu", role: "Sturmmagier", types: ["electric"], sprite: "pikachu",
    recolor: { "#ffcb05": "#f59e0b", "#f59e0b": "#d97706" }, scale: 1.12,
    base: [52, 22, 16, 12], grow: [4.0, 1.9, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"donnerwelle"],[1,"funkensprung"],[1,"donnerblitz"]],
  },
  glumanda: {
    dex: 4, name: "Glumanda", role: "Feuerritter", types: ["fire"], sprite: "glumanda",
    base: [40, 17, 13, 10], grow: [3.8, 1.8, 1.4, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[1,"glut"],[5,"feuerwirbel"],[9,"flammenwurf"]],
    evoLvl: 9, evoTo: "glutexo",
  },
  glutexo: {
    dex: 5, name: "Glutexo", role: "Flammenritter", types: ["fire"], sprite: "glumanda",
    recolor: { "#fb923c": "#ef4444", "#ea580c": "#b91c1c" }, scale: 1.12,
    base: [54, 23, 17, 11], grow: [4.2, 2.0, 1.6, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[1,"glut"],[1,"feuerwirbel"],[1,"flammenwurf"]],
  },
  schiggy: {
    dex: 7, name: "Schiggy", role: "Wassergarde", types: ["water"], sprite: "schiggy",
    base: [44, 15, 16, 9], grow: [4.0, 1.6, 1.7, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"tackle"],[1,"aquaknarre"],[4,"panzerschutz"],[7,"blubbstrahl"],[11,"hydropumpe"]],
    evoLvl: 10, evoTo: "schillok",
  },
  schillok: {
    dex: 8, name: "Schillok", role: "Flutgarde", types: ["water"], sprite: "schiggy",
    recolor: { "#60a5fa": "#6366f1", "#2563eb": "#4338ca" }, scale: 1.12,
    base: [58, 20, 22, 10], grow: [4.4, 1.8, 1.9, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"tackle"],[1,"aquaknarre"],[1,"panzerschutz"],[1,"blubbstrahl"],[11,"hydropumpe"]],
  },
  bisasam: {
    dex: 1, name: "Bisasam", role: "Druide", types: ["grass","poison"], sprite: "bisasam",
    base: [42, 16, 14, 9], grow: [3.9, 1.7, 1.5, 0], mov: 3, jmp: 2,
    learn: [[1,"tackle"],[1,"rankenhieb"],[4,"megasauger"],[7,"schlafpuder"],[10,"rasierblatt"]],
    evoLvl: 10, evoTo: "bisaknosp",
  },
  bisaknosp: {
    dex: 2, name: "Bisaknosp", role: "Erzdruide", types: ["grass","poison"], sprite: "bisasam",
    recolor: { "#22c55e": "#ec4899", "#15803d": "#be185d", "#2dd4bf": "#0d9488" }, scale: 1.12,
    base: [56, 21, 18, 10], grow: [4.3, 1.9, 1.7, 0], mov: 3, jmp: 2,
    learn: [[1,"tackle"],[1,"rankenhieb"],[1,"megasauger"],[1,"schlafpuder"],[1,"rasierblatt"]],
  },
  evoli: {
    dex: 133, name: "Evoli", role: "Weißmagier", types: ["normal"], sprite: "evoli",
    base: [40, 14, 13, 11], grow: [3.7, 1.5, 1.4, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"heilwoge"],[5,"sternschauer"],[8,"heuler"],[11,"bodyslam"]],
  },
  machollo: {
    dex: 66, name: "Machollo", role: "Mönch", types: ["fighting"], sprite: "machollo",
    base: [46, 19, 14, 9], grow: [4.2, 2.0, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[4,"protzer"],[8,"geowurf"]],
    evoLvl: 11, evoTo: "maschock",
  },
  maschock: {
    dex: 67, name: "Maschock", role: "Großmeister", types: ["fighting"], sprite: "machollo",
    recolor: { "#94a3b8": "#a78bfa", "#64748b": "#7c3aed" }, scale: 1.12,
    base: [60, 25, 18, 9], grow: [4.6, 2.2, 1.7, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[1,"protzer"],[1,"geowurf"],[1,"bodyslam"]],
  },
  abra: {
    dex: 63, name: "Abra", role: "Mystiker", types: ["psychic"], sprite: "abra",
    base: [34, 18, 9, 12], grow: [3.2, 2.0, 1.0, 0], mov: 4, jmp: 3,
    learn: [[1,"konfusion"],[5,"barriere"],[8,"psystrahl"],[12,"genesung"]],
    evoLvl: 12, evoTo: "kadabra",
  },
  kadabra: {
    dex: 64, name: "Kadabra", role: "Erzmystiker", types: ["psychic"], sprite: "abra",
    recolor: { "#fde047": "#fbbf24", "#a16207": "#78350f" }, scale: 1.12,
    base: [44, 24, 12, 13], grow: [3.6, 2.2, 1.2, 0], mov: 4, jmp: 3,
    learn: [[1,"konfusion"],[1,"barriere"],[1,"psystrahl"],[1,"genesung"],[1,"psychokinese"]],
  },
  nebulak: {
    dex: 92, name: "Nebulak", role: "Schattendieb", types: ["ghost","poison"], sprite: "nebulak",
    base: [36, 18, 10, 12], grow: [3.4, 1.9, 1.1, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"schlecker"],[1,"nachtnebel"],[6,"hypnose"],[10,"spukball"]],
    evoLvl: 11, evoTo: "alpollo",
  },
  alpollo: {
    dex: 93, name: "Alpollo", role: "Phantom", types: ["ghost","poison"], sprite: "nebulak",
    recolor: { "#a78bfa": "#7c3aed", "#6d28d9": "#4c1d95" }, scale: 1.12,
    base: [48, 23, 13, 13], grow: [3.8, 2.1, 1.3, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"schlecker"],[1,"nachtnebel"],[1,"hypnose"],[1,"spukball"]],
  },
  kleinstein: {
    dex: 74, name: "Kleinstein", role: "Steinwächter", types: ["rock","ground"], sprite: "kleinstein",
    base: [44, 18, 20, 6], grow: [4.0, 1.9, 2.0, 0], mov: 3, jmp: 1,
    learn: [[1,"steinwurf"],[4,"haertner"],[8,"intensitaet"],[11,"steinhagel"]],
    evoLvl: 11, evoTo: "georok",
  },
  georok: {
    dex: 75, name: "Georok", role: "Felsbastion", types: ["rock","ground"], sprite: "kleinstein",
    recolor: { "#a8a29e": "#78716c", "#78716c": "#44403c" }, scale: 1.18,
    base: [60, 23, 26, 6], grow: [4.4, 2.1, 2.2, 0], mov: 3, jmp: 1,
    learn: [[1,"steinwurf"],[1,"haertner"],[1,"intensitaet"],[1,"steinhagel"]],
  },
  relaxo: {
    dex: 143, name: "Relaxo", role: "Koloss", types: ["normal"], sprite: "relaxo",
    base: [70, 20, 18, 5], grow: [5.5, 2.0, 1.8, 0], mov: 3, jmp: 1,
    learn: [[1,"bodyslam"],[1,"erholung"],[1,"heuler"]],
  },

  /* === Gegner === */
  rattfratz: {
    dex: 19, name: "Rattfratz", role: "Plünderer", types: ["normal"], sprite: "rattfratz",
    base: [32, 14, 10, 10], grow: [3.0, 1.5, 1.1, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[3,"biss"],[6,"ruckzuck"]],
  },
  taubsi: {
    dex: 16, name: "Taubsi", role: "Späher", types: ["normal","flying"], sprite: "taubsi",
    base: [32, 13, 10, 11], grow: [3.0, 1.4, 1.1, 0], mov: 4, jmp: 4, fly: true,
    learn: [[1,"schnabel"],[3,"windstoss"],[7,"fluegelschlag"]],
  },
  zubat: {
    dex: 41, name: "Zubat", role: "Nachtjäger", types: ["poison","flying"], sprite: "zubat",
    base: [30, 14, 9, 12], grow: [2.9, 1.5, 1.0, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"biss"],[3,"superschall"],[6,"giftstachel"]],
  },
  rettan: {
    dex: 23, name: "Rettan", role: "Giftklinge", types: ["poison"], sprite: "rettan",
    base: [34, 15, 11, 9], grow: [3.2, 1.6, 1.2, 0], mov: 4, jmp: 2,
    learn: [[1,"giftstachel"],[4,"biss"],[7,"saeure"]],
  },
  sandan: {
    dex: 27, name: "Sandan", role: "Wüstenkrieger", types: ["ground"], sprite: "sandan",
    base: [38, 16, 14, 8], grow: [3.5, 1.7, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[4,"schaufler"],[8,"intensitaet"]],
  },
  tragosso: {
    dex: 104, name: "Tragosso", role: "Knochenwache", types: ["ground"], sprite: "tragosso",
    base: [40, 17, 15, 7], grow: [3.6, 1.8, 1.6, 0], mov: 3, jmp: 2,
    learn: [[1,"knochenkeule"],[5,"knochmerang"]],
  },
  magnetilo: {
    dex: 81, name: "Magnetilo", role: "Wachdrohne", types: ["electric"], sprite: "magnetilo",
    base: [34, 16, 14, 8], grow: [3.2, 1.7, 1.5, 0], mov: 3, jmp: 4, fly: true,
    learn: [[1,"donnerschock"],[5,"donnerwelle"],[9,"funkensprung"]],
  },
  onix: {
    dex: 95, name: "Onix", role: "Felskoloss", types: ["rock","ground"], sprite: "onix",
    base: [62, 18, 24, 6], grow: [5.0, 1.9, 2.2, 0], mov: 3, jmp: 2, boss: true,
    learn: [[1,"steinwurf"],[1,"tackle"],[6,"steinhagel"],[10,"intensitaet"]],
  },
  mewtu: {
    dex: 150, name: "Mewtu", role: "Champion", types: ["psychic"], sprite: "mewtu",
    base: [80, 23, 17, 13], grow: [5.0, 2.2, 1.7, 0], mov: 4, jmp: 3, boss: true,
    learn: [[1,"psystrahl"],[1,"psychoklinge"],[1,"genesung"],[1,"barriere"]],
  },
};

/* ---------- Pixel-Sprites (16×16) ----------
   '.' = transparent, 'k' = Kontur. Jedes Sprite: { pal, px } */
const SPRITES = {
  pikachu: {
    pal: { k:"#222034", y:"#ffcb05", o:"#f59e0b", r:"#ef4444", w:"#ffffff", n:"#b45309" },
    px: [
      "..k..........k..",
      ".kkk........kkk.",
      ".kykk......kkyk.",
      "..kykk....kkyk..",
      "..kyykkkkkkyyk..",
      "..kyyyyyyyyyyk..",
      ".kyykyyyyykyyk..",
      ".kyykyyyyykyyk..",
      ".kyryyyyyyyryk..",
      ".kyryyykkyyryk..",
      "..kyyyyyyyyyk...",
      "..kyyyyyyyyykkk.",
      ".kyyyyyyyyyknnk.",
      ".kyykyyyykyyknk.",
      ".kyykyyyykyykk..",
      "..kk..kk..kk....",
    ],
  },
  glumanda: {
    pal: { k:"#222034", o:"#fb923c", O:"#ea580c", c:"#fde68a", r:"#ef4444", f:"#fbbf24" },
    px: [
      "......kkkk......",
      ".....koooook....",
      "....koooooook...",
      "....kokoookok...",
      "....koooooook...",
      "....kookkoook...",
      ".....koooook....",
      "......koook..f..",
      ".....kooooookfk.",
      "....koocccookrk.",
      "...kooccccookk..",
      "...kooccccook...",
      "...kooccccook...",
      "....kooooook....",
      "....kok..kok....",
      ".....k....k.....",
    ],
  },
  schiggy: {
    pal: { k:"#222034", b:"#60a5fa", B:"#2563eb", s:"#fde68a", n:"#b45309" },
    px: [
      "......kkkk......",
      ".....kbbbbk.....",
      "....kbbbbbbk....",
      "...kbkbbbbkbk...",
      "...kbbbbbbbbk...",
      "...kbbkkkkbbk...",
      "....kbbbbbbk....",
      ".....kbbbbk.....",
      "....knnnnnnk....",
      "...knnssssnnk...",
      "..kbknssssknbk..",
      "..kbknssssknbk..",
      "...kknssssnkk...",
      "....knnnnnnk....",
      "....kbk..kbk....",
      ".....k....k.....",
    ],
  },
  bisasam: {
    pal: { k:"#222034", t:"#2dd4bf", T:"#0d9488", g:"#22c55e", G:"#15803d", r:"#ef4444" },
    px: [
      "......kkkk......",
      ".....kgGGgk.....",
      "....kgggggGk....",
      "...kgGgggGggk...",
      "...kGgggggGgk...",
      "....kgggggGk....",
      "..kkkkggggkkkk..",
      ".kttttkkkkttttk.",
      "ktttkttttttktttk",
      "kttkttttttttkttk",
      "kttkttkkkkttkttk",
      ".kttttttttttttk.",
      "..kttkttttkttk..",
      "..kttkttttkttk..",
      "...kk.kttk.kk...",
      ".......kk.......",
    ],
  },
  evoli: {
    pal: { k:"#222034", n:"#d97706", N:"#92400e", c:"#fef3c7" },
    px: [
      "..kk........kk..",
      ".knnk......knnk.",
      ".knNnk....knNnk.",
      ".knnnk....knnnk.",
      "..knnkkkkkknnk..",
      "..knnnnnnnnnnk..",
      ".knnknnnnnnknnk.",
      ".knnknnnnnnknnk.",
      ".knnnnnkknnnnnk.",
      "..knnnnnnnnnnk..",
      "...kncccccnnk...",
      "..knccccccnkkk..",
      "..knncccccnkNNk.",
      "..knnkcccknnkNk.",
      "..knnkcccknnkk..",
      "...kk.kk..kk....",
    ],
  },
  machollo: {
    pal: { k:"#222034", u:"#94a3b8", U:"#64748b" },
    px: [
      "....kkkkkkk.....",
      "...kuUUUUUuk....",
      "...kuuuuuuuk....",
      "...kukuuukuk....",
      "...kuuuuuuuk....",
      "...kuukkkuuk....",
      "....kuuuuuk.....",
      "..kkkuuuuukkk...",
      ".kuukuuuuukuuk..",
      ".kuukuuuuukuuk..",
      ".kuukuuuuukuuk..",
      "..kk.kuuuk.kk...",
      ".....kuuuk......",
      "....kuukuuk.....",
      "....kuukuuk.....",
      ".....kk.kk......",
    ],
  },
  abra: {
    pal: { k:"#222034", y:"#fde047", n:"#a16207" },
    px: [
      "...kk......kk...",
      "..kyyk....kyyk..",
      "..kyyyk..kyyyk..",
      "...kyyykkyyyk...",
      "...kyyyyyyyyk...",
      "...kykkyykkyk...",
      "...kyyyyyyyyk...",
      "....kyykkyyk....",
      ".....knnnnk.....",
      "....knnnnnnk....",
      "...kynnnnnnyk...",
      "..kyyknnnnkyyk..",
      "..kyyknnnnkyyk..",
      "...kkknnnnkkk...",
      ".....knk.knk....",
      "......k...k.....",
    ],
  },
  nebulak: {
    pal: { k:"#222034", v:"#a78bfa", V:"#6d28d9", w:"#ffffff" },
    px: [
      "....kk.kk.kk....",
      "...kvvkvvkvvk...",
      "..kvvvvvvvvvvk..",
      ".kvvVvvvvvvVvvk.",
      ".kvvvvvvvvvvvvk.",
      "kvvkwwkvvkwwkvvk",
      "kvvkwkkvvkwkkvvk",
      "kvvvvvvvvvvvvvvk",
      "kvvvvkkkkkkvvvvk",
      ".kvvvkwwwwkvvvk.",
      ".kvvvvkkkkvvvvk.",
      "..kvvvvvvvvvvk..",
      "...kvvkvvkvvk...",
      "....kk.kk.kk....",
      "................",
      "................",
    ],
  },
  kleinstein: {
    pal: { k:"#222034", s:"#a8a29e", S:"#78716c" },
    px: [
      "................",
      "....kkkkkkkk....",
      "...kssSssssSk...",
      "..kssssssssssk..",
      ".kSsskssskssssk.",
      ".kssskssskssssk.",
      "kssssssssssssssk",
      "ksksssskkssssksk",
      "kskssskssksskssk",
      "kssksssssssskssk",
      ".kskssskksssksk.",
      ".kkssssssssssкk.".replace("к","k"),
      "..kSssssssssSk..",
      "...kssssssssk...",
      "....kkkkkkkk....",
      "................",
    ],
  },
  relaxo: {
    pal: { k:"#222034", t:"#0f766e", T:"#134e4a", c:"#fef3c7" },
    px: [
      "...kk......kk...",
      "..kttkkkkkkttk..",
      "..kttttttttttk..",
      ".kttkttttttkttk.",
      ".kttttkkkkttttk.",
      ".ktttccccccttk..",
      ".kttccccccccttk.",
      "kttkccccccccкttk".replace("к","k"),
      "kttkccccccccкttk".replace("к","k"),
      "kttccccccccccttk",
      "kttccccccccccttk",
      ".kttccccccccttk.",
      ".kttkccccccкttk.".replace("к","k"),
      "..kkkccccccкkk..".replace("к","k"),
      "....kck..kck....",
      ".....k....k.....",
    ],
  },
  rattfratz: {
    pal: { k:"#222034", p:"#c084fc", P:"#7e22ce", c:"#fef3c7" },
    px: [
      "..kk........kk..",
      ".kppk......kppk.",
      ".kpPpk....kpPpk.",
      "..kppkkkkkkppk..",
      "..kppppppppppk..",
      ".kppkppppppkppk.",
      ".kppkppppppkppk.",
      ".kpppppkkpppppk.",
      "..kppppppppppk..",
      "...kpcccccppk...",
      "..kpcccccccpk...",
      "..kpcccccccpkkkk",
      "..kppcccccppk..k",
      "..kppkccckppk...",
      "...kk.kk..kk....",
      "................",
    ],
  },
  taubsi: {
    pal: { k:"#222034", n:"#d6a35c", N:"#9a6b2f", c:"#fef3c7", o:"#f97316" },
    px: [
      "......kkkk......",
      ".....knnnnk.....",
      "....knnnnnnk....",
      "...kNknnnnknk...",
      "...knnnnnnnnk...",
      "...knnnkkoook...",
      "....knnnnkok....",
      "..kkknnnnnkk....",
      ".kNNkncccnkNNk..",
      "kNNNkncccnkNNNk.",
      "kNNkncccccnkNNk.",
      ".kkncccccccnkk..",
      "..knncccccnnk...",
      "...knnnnnnnk....",
      "....kok.kok.....",
      ".....k...k......",
    ],
  },
  zubat: {
    pal: { k:"#222034", b:"#60a5fa", B:"#1d4ed8", m:"#a78bfa", w:"#ffffff" },
    px: [
      "kk............kk",
      "kBk..........kBk",
      "kBBk.kk..kk.kBBk",
      "kBBBkbbkkbbkBBBk",
      "kBBbbbbbbbbbbBBk",
      "kBbbbbbbbbbbbbBk",
      ".kBbbkbbbbkbbBk.",
      ".kBbbbbbbbbbbBk.",
      "..kBbbkmmkbbBk..",
      "..kBbbmmmmbbBk..",
      "...kBbkmmkbBk...",
      "...kBbbbbbbBk...",
      "....kkbbbbkk....",
      ".....kb..bk.....",
      ".....k....k.....",
      "................",
    ],
  },
  rettan: {
    pal: { k:"#222034", p:"#c084fc", P:"#7e22ce", y:"#fde047" },
    px: [
      "....kkkkk.......",
      "...kpppppk......",
      "..kppkppkpk.....",
      "..kpppppppk.....",
      "..kppkkkppk.....",
      "...kpyyypk......",
      "....kpppk.......",
      ".....kpppk......",
      "......kpppk.....",
      ".......kpppkkk..",
      "....kkkkpppppPk.",
      "...kPpppppppPPk.",
      "..kPpppkkkppPk..",
      "..kPppk...kkk...",
      "...kkk..........",
      "................",
    ],
  },
  sandan: {
    pal: { k:"#222034", y:"#facc15", Y:"#a16207", c:"#fef3c7" },
    px: [
      "...kk....kk.....",
      "..kyYk..kYyk....",
      "..kyyykkyyyk....",
      "..kyyyyyyyyk....",
      ".kyykyyyykyyk...",
      ".kyyyyyyyyyyk...",
      ".kyyykkkyyyyk...",
      "..kyyyyyyyykk...",
      "..kYyccccyykYk..",
      ".kYyccccccyykYk.",
      ".kYyccccccyykk..",
      ".kYyccccccyyk...",
      "..kycccccyyk....",
      "..kyykccckyyk...",
      "...kk.kk..kk....",
      "................",
    ],
  },
  tragosso: {
    pal: { k:"#222034", c:"#e7e5e4", C:"#a8a29e", n:"#d6a35c", N:"#9a6b2f" },
    px: [
      "....kkkkkkk.....",
      "...kcccccccк....".replace("к","k"),
      "..kccCcccCcck...",
      "..kccccccccck...",
      ".kcckccccкcccк..".replace(/к/g,"k"),
      ".kcckkccckkcck..",
      ".kcccccccccccк..".replace("к","k"),
      "..kccckkkcccк...".replace("к","k"),
      "...kknnnnnkk....",
      "...knnnnnnnk..kk",
      "..knnknnnknnkkck",
      "..knnnnnnnnnkck.",
      "..knnknnnknnck..",
      "...kk.knk.kk....",
      "......kkk.......",
      "................",
    ],
  },
  magnetilo: {
    pal: { k:"#222034", s:"#cbd5e1", S:"#64748b", r:"#ef4444", b:"#3b82f6", w:"#ffffff" },
    px: [
      "kk............kk",
      "krk....kk....kbk",
      "krk...kssk...kbk",
      "krkkkkssssкkkbk.".replace("к","k"),
      "krrrkssssssкbbbk".replace("к","k"),
      "kkkkssssssssкkkk".replace("к","k"),
      "...ksskwwkssk...",
      "...ksskwkkssk...",
      "...ksssкksssk...".replace("к","k"),
      "....kssssssk....",
      ".....kssssk.....",
      "....kkSSSSкk....".replace("к","k"),
      "....kSkkkkSk....",
      ".....k....k.....",
      "................",
      "................",
    ],
  },
  onix: {
    pal: { k:"#222034", s:"#9ca3af", S:"#4b5563" },
    px: [
      "....kkkkkk......",
      "...kssssssk.....",
      "..kskssskssk....",
      ".kssssssssssk...",
      ".kssкkkкssssk...".replace(/к/g,"k"),
      ".kssssssssssk...",
      "..ksskkkkssk....",
      "...kssssssk.....",
      "....kSSSSSSk....",
      "...kSSSSSSSSk...",
      "..kSSSkSSкSSSk..".replace("к","k"),
      "..kSSSSSSSSSSk..",
      ".kSSSSkSSkSSSSk.",
      ".kSSSSSSSSSSSSk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  mewtu: {
    pal: { k:"#222034", g:"#e2d9f3", G:"#b8a6d9", v:"#7c3aed" },
    px: [
      "..kk........kk..",
      ".kggk......kggk.",
      ".kgggkkkkkkgggk.",
      "..kgggggggggk...",
      "..kgkggggkggk...",
      "..kgvggggvggk...",
      "..kggggggggk....",
      "...kggkkggk.....",
      "....kggggk..kkk.",
      "...kggggggkkvvk.",
      "..kggkggggkvvk..",
      "..kggkggggvvk...",
      "..kggkggggk.....",
      "...kkgggggk.....",
      "....kgk.kgk.....",
      ".....k...k......",
    ],
  },
};

/* ---------- Gelände ---------- */
const TERRAIN = {
  g: { name: "Gras",         top: "#5cb85c", top2: "#4cae4c", side: "#3e8e41", side2: "#2d6a2f" },
  G: { name: "Dichtes Gras", top: "#3f9142", top2: "#357a38", side: "#2d6a2f", side2: "#1f4a21" },
  d: { name: "Erde",         top: "#c89b6a", top2: "#b8895a", side: "#9a6b3f", side2: "#7a532f" },
  s: { name: "Stein",        top: "#9aa3b2", top2: "#8a93a2", side: "#6b7280", side2: "#525a66" },
  S: { name: "Fels",         top: "#7c8494", top2: "#6c7484", side: "#4e5564", side2: "#3a4050" },
  w: { name: "Wasser",       top: "#3b82f6", top2: "#2563eb", side: "#1d4ed8", side2: "#1e3a8a", water: true },
  b: { name: "Steg",         top: "#b08350", top2: "#9a7340", side: "#7a5a32", side2: "#5e4526" },
  p: { name: "Spukstein",    top: "#6b5b95", top2: "#5b4b85", side: "#4a3d70", side2: "#382e55" },
  P: { name: "Dunkelstein",  top: "#534578", top2: "#473a68", side: "#382e55", side2: "#2a2240" },
};

/* ---------- Schlachten ---------- */
const BATTLES = [
  {
    id: 0, name: "Grüne Ebene", icon: "🌿",
    desc: "Wilde Pokémon versperren den Weg. Ein sanfter Einstieg.",
    intro: "Wilde Pokémon greifen an!\nBesiege alle Gegner.",
    partySize: 3,
    heights: [
      "001111000",
      "001122100",
      "000122100",
      "000111100",
      "000011000",
      "000000000",
      "000000011",
      "000000111",
      "000000111",
    ],
    terrain: [
      "ggggggggg",
      "ggGGgggdg",
      "ggGGggddg",
      "gggggggdg",
      "ggggggggg",
      "gGgggggGg",
      "gggggggGG",
      "ggdddggGG",
      "ggdddgggG",
    ],
    spawns: [[1,7],[2,8],[1,6],[3,8]],
    enemies: [
      { sp: "rattfratz", lvl: 2, x: 6, y: 1 },
      { sp: "rattfratz", lvl: 2, x: 4, y: 2 },
      { sp: "taubsi",    lvl: 2, x: 7, y: 3 },
    ],
    exp: 90, recruit: { sp: "machollo", lvl: 3 },
  },
  {
    id: 1, name: "Flussfurt", icon: "🌊",
    desc: "Ein reißender Fluss – nur die Brücke führt hinüber.",
    intro: "Gegner lauern am anderen Ufer.\nWasser-Pokémon können schwimmen!",
    partySize: 4,
    heights: [
      "1100000011",
      "1100000011",
      "0000000001",
      "0000000000",
      "0000110000",
      "0000000000",
      "0000000011",
      "1000000011",
      "1100000111",
    ],
    terrain: [
      "ggggwwgggg",
      "ggggwwgggg",
      "gGggwwggGg",
      "ggggwwgggg",
      "ggggbbgggg",
      "ggggwwgggg",
      "gggGwwgggg",
      "ggggwwggGg",
      "ggggwwgggg",
    ],
    spawns: [[1,3],[1,5],[2,4],[0,4]],
    enemies: [
      { sp: "taubsi", lvl: 3, x: 7, y: 2 },
      { sp: "rettan", lvl: 3, x: 8, y: 4 },
      { sp: "zubat",  lvl: 3, x: 7, y: 6 },
      { sp: "rattfratz", lvl: 3, x: 8, y: 5 },
    ],
    exp: 110, recruit: { sp: "abra", lvl: 4 },
  },
  {
    id: 2, name: "Felsschlucht", icon: "⛰",
    desc: "Steile Klippen – wer oben steht, hat den Vorteil.",
    intro: "Die Gegner halten die Höhen besetzt.\nErobere die Schlucht!",
    partySize: 4,
    heights: [
      "3332100123",
      "3322100123",
      "2221000122",
      "1110000011",
      "0000000000",
      "1100000011",
      "2210000122",
      "3321001223",
      "3332101233",
    ],
    terrain: [
      "ssssddssss",
      "ssssddssss",
      "sssdddssss",
      "sdddddddss",
      "dddddddddd",
      "sdddddddds",
      "ssddddddss",
      "ssssdddsss",
      "ssssddssss",
    ],
    spawns: [[4,8],[5,8],[3,8],[6,8],[4,7]],
    enemies: [
      { sp: "sandan",   lvl: 4, x: 2, y: 1 },
      { sp: "tragosso", lvl: 4, x: 7, y: 1 },
      { sp: "rettan",   lvl: 4, x: 4, y: 2 },
      { sp: "sandan",   lvl: 4, x: 5, y: 1 },
      { sp: "tragosso", lvl: 5, x: 5, y: 0 },
    ],
    exp: 130, recruit: { sp: "evoli", lvl: 5 },
  },
  {
    id: 3, name: "Spukturm", icon: "👻",
    desc: "Im alten Turm flackern unheimliche Lichter.",
    intro: "Geister-Pokémon erscheinen!\nNormale Hiebe verpuffen an ihnen …",
    partySize: 5,
    heights: [
      "011001100",
      "112112110",
      "122222210",
      "012333210",
      "012343210",
      "012333210",
      "012222210",
      "011111110",
      "000000000",
    ],
    terrain: [
      "pPPpppPPp",
      "pppppppPp",
      "pPpppppPp",
      "ppppPpppp",
      "pPppppppP",
      "ppppPpppp",
      "pPpppppPp",
      "ppppppppp",
      "PppPpppPP",
    ],
    spawns: [[3,8],[5,8],[4,8],[2,8],[6,8]],
    enemies: [
      { sp: "nebulak", lvl: 5, x: 3, y: 3 },
      { sp: "nebulak", lvl: 5, x: 5, y: 3 },
      { sp: "zubat",   lvl: 5, x: 1, y: 2 },
      { sp: "zubat",   lvl: 5, x: 7, y: 2 },
      { sp: "nebulak", lvl: 6, x: 4, y: 4, boss: true },
    ],
    exp: 150, recruit: { sp: "nebulak", lvl: 7 },
  },
  {
    id: 4, name: "Donnerplateau", icon: "⚡",
    desc: "Magnetische Wachdrohnen patrouillieren auf den Terrassen.",
    intro: "Die Drohnen schweben über jede Klippe.\nVorsicht vor Paralyse!",
    partySize: 5,
    heights: [
      "2223333222",
      "2223333222",
      "1122222211",
      "1111221111",
      "0011111100",
      "0000110000",
      "0000000000",
      "0000000000",
      "1100000011",
    ],
    terrain: [
      "ssssSSssss",
      "ssssSSssss",
      "dsssssssds",
      "ddssssssdd",
      "dddssssddd",
      "ddddssdddd",
      "dddddddddd",
      "gddddddddg",
      "ggddddddgg",
    ],
    spawns: [[3,8],[6,8],[4,8],[5,8],[2,8]],
    enemies: [
      { sp: "magnetilo", lvl: 6, x: 2, y: 2 },
      { sp: "magnetilo", lvl: 6, x: 7, y: 2 },
      { sp: "magnetilo", lvl: 7, x: 4, y: 1 },
      { sp: "tragosso",  lvl: 7, x: 5, y: 2 },
      { sp: "onix",      lvl: 7, x: 5, y: 0, boss: true },
    ],
    exp: 170, recruit: { sp: "kleinstein", lvl: 8 },
  },
  {
    id: 5, name: "Arena der Rivalen", icon: "⚔",
    desc: "Das Rivalen-Team fordert dich zum Duell.",
    intro: "Ein ebenbürtiges Team!\nSie kennen dieselben Tricks wie du.",
    partySize: 5,
    heights: [
      "311111113",
      "111111111",
      "111222111",
      "112222211",
      "112232211",
      "112222211",
      "111222111",
      "111111111",
      "311111113",
    ],
    terrain: [
      "Sssssssss",
      "sssssssss",
      "ssGGGGGss",
      "ssGgggGss",
      "ssGgggGss",
      "ssGgggGss",
      "ssGGGGGss",
      "sssssssss",
      "SssssssSS",
    ],
    spawns: [[3,8],[5,8],[4,8],[2,8],[6,8]],
    enemies: [
      { sp: "glutexo",  lvl: 8,  x: 4, y: 0, boss: true },
      { sp: "schillok", lvl: 8,  x: 2, y: 0 },
      { sp: "bisaknosp",lvl: 8,  x: 6, y: 0 },
      { sp: "raichu",   lvl: 8,  x: 4, y: 1 },
    ],
    exp: 200, recruit: { sp: "relaxo", lvl: 9 },
  },
  {
    id: 6, name: "Zitadelle des Champions", icon: "👑",
    desc: "Auf dem höchsten Thron wartet Mewtu.",
    intro: "Mewtu erhebt sich.\n»Zeigt mir eure Stärke – oder zerbrecht.«",
    partySize: 5,
    heights: [
      "2211111122",
      "2111111112",
      "1112222111",
      "1123333211",
      "1123443211",
      "1123333211",
      "1112222111",
      "1111111111",
      "0000000000",
    ],
    terrain: [
      "PPppppppPP",
      "PppppppppP",
      "pppPPPPppp",
      "ppPsssssPp",
      "ppPssssspP",
      "ppPsssssPp",
      "pppPPPPppp",
      "pppppppppp",
      "pppppppppp",
    ],
    spawns: [[3,8],[6,8],[4,8],[5,8],[2,8]],
    enemies: [
      { sp: "kadabra", lvl: 8, x: 2, y: 3 },
      { sp: "alpollo", lvl: 8, x: 7, y: 3 },
      { sp: "onix",    lvl: 8, x: 4, y: 2 },
      { sp: "magnetilo", lvl: 8, x: 5, y: 2 },
      { sp: "mewtu",   lvl: 10, x: 4, y: 4, boss: true },
    ],
    exp: 250,
  },
];

/* ---------- Kampagnen-Konstanten ---------- */
const START_ROSTER = [
  { sp: "pikachu",  lvl: 3 },
  { sp: "glumanda", lvl: 3 },
  { sp: "schiggy",  lvl: 3 },
  { sp: "bisasam",  lvl: 3 },
];
const EXP_PER_LEVEL = 100;
const SAVE_KEY = "poketactics_save_v1";
