/* ============================================================
   PokéTactics – Spieldaten
   Typen, Attacken, Spezies, Sprites, Schlachten
   ============================================================ */
"use strict";

/* ---------- Typen ---------- */
const TYPES = {
  normal:   { name: "Normal",   color: "#9ca3af" },
  fire:     { name: "Feuer",    color: "#f97316", ice: 2, bug: 2 },
  water:    { name: "Wasser",   color: "#3b82f6" },
  grass:    { name: "Pflanze",  color: "#22c55e" },
  electric: { name: "Elektro",  color: "#eab308" },
  psychic:  { name: "Psycho",   color: "#ec4899" },
  fighting: { name: "Kampf",    color: "#b91c1c", ice: 2 },
  rock:     { name: "Gestein",  color: "#a16207", ice: 2, bug: 2 },
  ground:   { name: "Boden",    color: "#d97706" },
  flying:   { name: "Flug",     color: "#818cf8", bug: 2 },
  poison:   { name: "Gift",     color: "#a855f7" },
  ghost:    { name: "Geist",    color: "#6d28d9" },
  ice:      { name: "Eis",      color: "#7dd3fc",  },
  bug:      { name: "Käfer",    color: "#84cc16" },
  dragon:   { name: "Drache",   color: "#6366f1" },
};

/* Angriffstyp -> { Verteidigertyp: Multiplikator }, fehlend = 1 */
const TYPE_CHART = {
  normal:   { rock: .5, ghost: 0 },
  fire:     { grass: 2, ice: 2, bug: 2, water: .5, fire: .5, rock: .5 },
  water:    { fire: 2, rock: 2, ground: 2, water: .5, grass: .5 },
  grass:    { water: 2, rock: 2, ground: 2, fire: .5, grass: .5, flying: .5, poison: .5 },
  electric: { water: 2, flying: 2, grass: .5, electric: .5, ground: 0 },
  psychic:  { fighting: 2, poison: 2, psychic: .5 },
  fighting: { normal: 2, rock: 2, ice: 2, flying: .5, psychic: .5, poison: .5, ghost: 0 },
  rock:     { fire: 2, flying: 2, ice: 2, bug: 2, fighting: .5, ground: .5 },
  ground:   { fire: 2, electric: 2, rock: 2, poison: 2, grass: .5, flying: 0 },
  flying:   { grass: 2, fighting: 2, bug: 2, electric: .5, rock: .5 },
  poison:   { grass: 2, poison: .5, ground: .5, rock: .5, ghost: .5 },
  ghost:    { ghost: 2, psychic: 2, normal: 0 },
  ice:      { grass: 2, ground: 2, flying: 2, dragon: 2, water: .5, fire: .5, ice: .5 },
  bug:      { grass: 2, psychic: 2, fire: .5, fighting: .5, flying: .5, poison: .5, ghost: .5 },
  dragon:   { dragon: 2 },
};

function typeMult(atkType, defTypes) {
  let m = 1;
  for (const dt of defTypes) {
    const row = TYPE_CHART[atkType];
    if (row && row[dt] !== undefined) m *= row[dt];
  }
  return m;
}

/* ---------- Status ---------- */
const STATUS = {
  brn: { name: "Brand",    icon: "🔥", color: "#fdba74" },
  psn: { name: "Gift",     icon: "☠",  color: "#d8b4fe" },
  par: { name: "Paralyse", icon: "⚡", color: "#fde047" },
  slp: { name: "Schlaf",   icon: "💤", color: "#93c5fd" },
};

/* ---------- Attacken ----------
   cat: 'p' physisch, 'm' speziell, 's' status
   rng: Reichweite (0 = selbst/Umkreis), aoe: 0 einzeln, 1 Kreuz, 2 Umkreis
   target: foe | ally | self
*/
const MOVES = {
  hieb:        { name: "Hieb",        type: "normal",  cat: "p", pow: 35, rng: 1, aoe: 0, acc: 95, pp: Infinity, target: "foe", desc: "Einfacher Nahkampfangriff." },

  tackle:      { name: "Tackle",      type: "normal",  cat: "p", pow: 45, rng: 1, aoe: 0, acc: 95, pp: 20, knock: 1, target: "foe", desc: "Rammt das Ziel mit vollem Körpereinsatz." },
  ruckzuck:    { name: "Ruckzuckhieb",type: "normal",  cat: "p", pow: 40, rng: 2, aoe: 0, acc: 100, pp: 12, target: "foe", desc: "Blitzschneller Sturmangriff über 2 Felder." },
  bodyslam:    { name: "Bodyslam",    type: "normal",  cat: "p", pow: 70, rng: 1, aoe: 0, acc: 90, pp: 8, knock: 2, fx: { st: "par", ch: 30 }, target: "foe", desc: "Schwerer Körperpresser, schleudert zurück & kann paralysieren." },
  sternschauer:{ name: "Sternschauer",type: "normal",  cat: "m", pow: 55, rng: 3, aoe: 0, acc: 999, pp: 10, target: "foe", desc: "Sterne, die niemals verfehlen." },
  heuler:      { name: "Heuler",      type: "normal",  cat: "s", pow: 0,  rng: 2, aoe: 1, acc: 100, pp: 8, buff: { stat: "atk", mult: .7, dur: 3 }, target: "foe", desc: "Senkt den Angriff der Gegner im Umkreis." },
  erholung:    { name: "Erholung",    type: "normal",  cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 3, heal: 1, fx: { st: "slp", ch: 100, self: true }, target: "self", desc: "Heilt vollständig, aber schläfert selbst ein." },

  donnerschock:{ name: "Donnerschock",type: "electric",cat: "m", pow: 50, rng: 3, aoe: 0, acc: 95, pp: 15, fx: { st: "par", ch: 10 }, target: "foe", desc: "Elektroschock auf Distanz." },
  donnerblitz: { name: "Donnerblitz", type: "electric",cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, fx: { st: "par", ch: 15 }, target: "foe", desc: "Mächtiger Blitzschlag, kann paralysieren." },
  donnerwelle: { name: "Donnerwelle", type: "electric",cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 85, pp: 8, fx: { st: "par", ch: 100 }, target: "foe", desc: "Paralysiert das Ziel zuverlässig." },
  funkensprung:{ name: "Funkensprung",type: "electric",cat: "m", pow: 60, rng: 2, aoe: 1, acc: 90, pp: 6, target: "foe", desc: "Entlädt Funken im Kreuzbereich." },

  glut:        { name: "Glut",        type: "fire",    cat: "m", pow: 50, rng: 2, aoe: 0, acc: 95, pp: 15, fx: { st: "brn", ch: 15 }, target: "foe", desc: "Kleine Flamme, kann Brand verursachen." },
  flammenwurf: { name: "Flammenwurf", type: "fire",    cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, fx: { st: "brn", ch: 20 }, target: "foe", desc: "Heißer Flammenstrahl." },
  feuerwirbel: { name: "Feuerwirbel", type: "fire",    cat: "m", pow: 55, rng: 2, aoe: 1, acc: 90, pp: 6, fx: { st: "brn", ch: 15 }, target: "foe", desc: "Flammen im Kreuzbereich." },

  aquaknarre:  { name: "Aquaknarre",  type: "water",   cat: "m", pow: 50, rng: 3, aoe: 0, acc: 95, pp: 15, target: "foe", desc: "Gezielter Wasserstrahl." },
  blubbstrahl: { name: "Blubbstrahl", type: "water",   cat: "m", pow: 65, rng: 3, aoe: 0, acc: 95, pp: 10, buff: { stat: "spd", mult: .75, dur: 2 }, target: "foe", desc: "Blasen, die das Ziel verlangsamen." },
  hydropumpe:  { name: "Hydropumpe",  type: "water",   cat: "m", pow: 90, rng: 3, aoe: 0, acc: 80, pp: 5, knock: 2, target: "foe", desc: "Gewaltige Wasserkanone, die wegspült." },
  panzerschutz:{ name: "Panzerschutz",type: "water",   cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 6, buff: { stat: "def", mult: 1.5, dur: 3 }, target: "self", desc: "Erhöht die eigene Verteidigung stark." },

  rankenhieb:  { name: "Rankenhieb",  type: "grass",   cat: "p", pow: 50, rng: 2, aoe: 0, acc: 100, pp: 15, target: "foe", desc: "Peitscht mit Ranken über 2 Felder." },
  rasierblatt: { name: "Rasierblatt", type: "grass",   cat: "p", pow: 60, rng: 3, aoe: 1, acc: 90, pp: 8, target: "foe", desc: "Blätterhagel im Kreuzbereich." },
  megasauger:  { name: "Megasauger",  type: "grass",   cat: "m", pow: 45, rng: 2, aoe: 0, acc: 100, pp: 10, drain: .6, target: "foe", desc: "Saugt KP ab und heilt sich selbst." },
  schlafpuder: { name: "Schlafpuder", type: "grass",   cat: "s", pow: 0,  rng: 2, aoe: 0, acc: 70, pp: 6, fx: { st: "slp", ch: 100 }, target: "foe", desc: "Schläfert das Ziel ein." },

  konfusion:   { name: "Konfusion",   type: "psychic", cat: "m", pow: 55, rng: 3, aoe: 0, acc: 95, pp: 15, target: "foe", desc: "Telekinetischer Stoß." },
  psystrahl:   { name: "Psystrahl",   type: "psychic", cat: "m", pow: 70, rng: 3, aoe: 0, acc: 95, pp: 8, target: "foe", desc: "Schillernder Psycho-Strahl." },
  psychokinese:{ name: "Psychokinese",type: "psychic", cat: "m", pow: 78, rng: 3, aoe: 1, acc: 90, pp: 5, target: "foe", desc: "Gewaltige Psycho-Druckwelle." },
  genesung:    { name: "Genesung",    type: "psychic", cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 5, heal: .5, target: "self", desc: "Heilt die Hälfte der eigenen max. KP." },
  barriere:    { name: "Barriere",    type: "psychic", cat: "s", pow: 0,  rng: 2, aoe: 0, acc: 100, pp: 6, buff: { stat: "def", mult: 1.4, dur: 3 }, target: "ally", desc: "Schützt einen Verbündeten." },
  hypnose:     { name: "Hypnose",     type: "psychic", cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 65, pp: 6, fx: { st: "slp", ch: 100 }, target: "foe", desc: "Hypnotisiert das Ziel in den Schlaf." },

  karateschlag:{ name: "Karateschlag",type: "fighting",cat: "p", pow: 55, rng: 1, aoe: 0, acc: 95, pp: 15, crit: 15, knock: 1, target: "foe", desc: "Präziser Schlag, oft Volltreffer." },
  geowurf:     { name: "Geowurf",     type: "fighting",cat: "p", pow: 70, rng: 1, aoe: 0, acc: 90, pp: 8, knock: 3, target: "foe", desc: "Schleudert das Ziel weit zu Boden." },
  protzer:     { name: "Protzer",     type: "fighting",cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 6, buff: { stat: "atk", mult: 1.4, dur: 3 }, target: "self", desc: "Pumpt sich auf: Angriff steigt." },

  schlecker:   { name: "Schlecker",   type: "ghost",   cat: "p", pow: 35, rng: 1, aoe: 0, acc: 100, pp: 15, fx: { st: "par", ch: 30 }, target: "foe", desc: "Eklige Zunge, kann paralysieren." },
  nachtnebel:  { name: "Nachtnebel",  type: "ghost",   cat: "m", pow: 55, rng: 3, aoe: 0, acc: 95, pp: 12, target: "foe", desc: "Unheimlicher Schattenstoß." },
  spukball:    { name: "Spukball",    type: "ghost",   cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, target: "foe", desc: "Geballte Schattenenergie." },

  steinwurf:   { name: "Steinwurf",   type: "rock",    cat: "p", pow: 55, rng: 3, aoe: 0, acc: 90, pp: 12, knock: 1, target: "foe", desc: "Wirft einen Felsbrocken." },
  steinhagel:  { name: "Steinhagel",  type: "rock",    cat: "p", pow: 65, rng: 3, aoe: 1, acc: 85, pp: 6, target: "foe", desc: "Steinschlag im Kreuzbereich." },
  haertner:    { name: "Härtner",     type: "rock",    cat: "s", pow: 0,  rng: 0, aoe: 0, acc: 100, pp: 8, buff: { stat: "def", mult: 1.4, dur: 3 }, target: "self", desc: "Verhärtet den Körper." },

  knochenkeule:{ name: "Knochenkeule",type: "ground",  cat: "p", pow: 60, rng: 1, aoe: 0, acc: 95, pp: 12, knock: 1, target: "foe", desc: "Schlag mit der Knochenkeule." },
  knochmerang: { name: "Knochmerang", type: "ground",  cat: "p", pow: 55, rng: 3, aoe: 0, acc: 90, pp: 8, target: "foe", desc: "Geworfener Knochen-Bumerang." },
  intensitaet: { name: "Intensität",  type: "ground",  cat: "p", pow: 60, rng: 0, aoe: 2, acc: 95, pp: 6, knock: 1, target: "foe", desc: "Erdbeben rund um den Anwender." },
  schaufler:   { name: "Schaufler",   type: "ground",  cat: "p", pow: 65, rng: 2, aoe: 0, acc: 95, pp: 8, target: "foe", desc: "Angriff aus dem Untergrund." },

  windstoss:   { name: "Windstoß",    type: "flying",  cat: "m", pow: 45, rng: 3, aoe: 0, acc: 95, pp: 15, target: "foe", desc: "Schneidende Windböe." },
  fluegelschlag:{ name:"Flügelschlag",type: "flying",  cat: "p", pow: 60, rng: 2, aoe: 0, acc: 95, pp: 10, knock: 1, target: "foe", desc: "Schlag mit harten Schwingen." },
  schnabel:    { name: "Schnabel",    type: "flying",  cat: "p", pow: 45, rng: 1, aoe: 0, acc: 100, pp: 15, target: "foe", desc: "Pickt mit spitzem Schnabel." },

  giftstachel: { name: "Giftstachel", type: "poison",  cat: "p", pow: 40, rng: 2, aoe: 0, acc: 95, pp: 15, fx: { st: "psn", ch: 30 }, target: "foe", desc: "Giftiger Stich." },
  saeure:      { name: "Säure",       type: "poison",  cat: "m", pow: 50, rng: 2, aoe: 1, acc: 90, pp: 8, fx: { st: "psn", ch: 20 }, target: "foe", desc: "Ätzende Säure im Kreuzbereich." },
  biss:        { name: "Biss",        type: "normal",  cat: "p", pow: 55, rng: 1, aoe: 0, acc: 95, pp: 12, target: "foe", desc: "Kräftiger Biss." },
  superschall: { name: "Superschall", type: "flying",  cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 75, pp: 8, buff: { stat: "atk", mult: .65, dur: 3 }, target: "foe", desc: "Schrille Wellen schwächen den Angriff." },

  heilwoge:    { name: "Heilwoge",    type: "psychic", cat: "s", pow: 0,  rng: 3, aoe: 0, acc: 100, pp: 8, heal: .45, target: "ally", desc: "Heilt einen Verbündeten (45 % max. KP)." },

  // Eis
  eishieb:     { name: "Eishieb",     type: "ice",     cat: "p", pow: 55, rng: 1, aoe: 0, acc: 95, pp: 12, knock: 1, buff: { stat: "spd", mult: .8, dur: 2 }, target: "foe", desc: "Eiskalter Hieb, verlangsamt das Ziel." },
  eisstrahl:   { name: "Eisstrahl",   type: "ice",     cat: "m", pow: 75, rng: 3, aoe: 0, acc: 95, pp: 8, buff: { stat: "spd", mult: .7, dur: 2 }, target: "foe", desc: "Kalter Strahl, der das Ziel einfriert (langsamer)." },
  schneesturm: { name: "Schneesturm", type: "ice",     cat: "m", pow: 60, rng: 3, aoe: 1, acc: 85, pp: 5, target: "foe", desc: "Eisige Böen im Kreuzbereich." },
  aurorastrahl:{ name: "Aurorastrahl",type: "ice",     cat: "m", pow: 55, rng: 3, aoe: 0, acc: 100, pp: 10, target: "foe", desc: "Schimmernder Eisstrahl." },

  // Käfer
  käfersäbel:  { name: "Käfersäbel",  type: "bug",     cat: "p", pow: 55, rng: 1, aoe: 0, acc: 95, pp: 15, crit: 12, target: "foe", desc: "Schnelle Klingenhiebe, oft Volltreffer." },
  käferbiss:   { name: "Käferbiss",   type: "bug",     cat: "p", pow: 50, rng: 1, aoe: 0, acc: 100, pp: 12, drain: .5, target: "foe", desc: "Saugt mit den Mandibeln KP ab." },
  zornklinge:  { name: "Zornklinge",  type: "bug",     cat: "p", pow: 70, rng: 2, aoe: 0, acc: 90, pp: 8, target: "foe", desc: "Sichelhieb über zwei Felder." },

  // Drache
  drachenklaue:{ name: "Drachenklaue",type: "dragon",  cat: "p", pow: 65, rng: 1, aoe: 0, acc: 100, pp: 10, target: "foe", desc: "Reißt mit gewaltigen Klauen." },
  drachenwut:  { name: "Drachenwut",  type: "dragon",  cat: "m", pow: 65, rng: 3, aoe: 0, acc: 100, pp: 8, target: "foe", desc: "Eine Druckwelle aus reiner Drachenkraft." },
  wutanfall:   { name: "Wutanfall",   type: "dragon",  cat: "p", pow: 90, rng: 1, aoe: 0, acc: 90, pp: 5, knock: 2, target: "foe", desc: "Tobender Angriff mit voller Wucht." },
  platscher:   { name: "Platscher",   type: "normal",  cat: "p", pow: 12, rng: 1, aoe: 0, acc: 100, pp: Infinity, target: "foe", desc: "Platsch, platsch … fast völlig wirkungslos. Karpador eben." },
  psychoklinge:{ name: "Psychoklinge",type: "psychic", cat: "m", pow: 72, rng: 4, aoe: 1, acc: 95, pp: 6, target: "foe", desc: "Mewtus verheerende Psycho-Klinge." },
};

/* ---------- Spezies ----------
   base: [KP, ANG, VER, TEMPO], grow: Zuwachs pro Level
   mov: Bewegung, jmp: Sprunghöhe, fly: schwebt, swim: darf ins Wasser
*/
const SPECIES = {
  /* === Spieler-Pokémon === */
  pikachu: {
    dex: 25, name: "Pikachu", role: "Blitzmagier", types: ["electric"], sprite: "pikachu",
    base: [38, 16, 12, 11], grow: [3.6, 1.7, 1.3, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"donnerschock"],[4,"donnerwelle"],[7,"funkensprung"],[10,"donnerblitz"]],
    evoLvl: 12, evoTo: "raichu",
  },
  raichu: {
    dex: 26, name: "Raichu", role: "Sturmmagier", types: ["electric"], sprite: "pikachu",
    recolor: { "#ffcb05": "#f59e0b", "#f59e0b": "#d97706" }, scale: 1.12,
    base: [52, 22, 16, 12], grow: [4.0, 1.9, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"donnerwelle"],[1,"funkensprung"],[1,"donnerblitz"]],
  },
  glumanda: {
    dex: 4, name: "Glumanda", role: "Feuerritter", types: ["fire"], sprite: "glumanda",
    base: [40, 17, 13, 10], grow: [3.8, 1.8, 1.4, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[1,"glut"],[5,"feuerwirbel"],[9,"flammenwurf"]],
    evoLvl: 9, evoTo: "glutexo",
  },
  glutexo: {
    dex: 5, name: "Glutexo", role: "Flammenritter", types: ["fire"], sprite: "glumanda", evoTo: "glurak",
    recolor: { "#fb923c": "#ef4444", "#ea580c": "#b91c1c" }, scale: 1.12,
    base: [54, 23, 17, 11], grow: [4.2, 2.0, 1.6, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[1,"glut"],[1,"feuerwirbel"],[1,"flammenwurf"]],
  },
  schiggy: {
    dex: 7, name: "Schiggy", role: "Wassergarde", types: ["water"], sprite: "schiggy",
    base: [44, 15, 16, 9], grow: [4.0, 1.6, 1.7, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"tackle"],[1,"aquaknarre"],[4,"panzerschutz"],[7,"blubbstrahl"],[11,"hydropumpe"]],
    evoLvl: 10, evoTo: "schillok",
  },
  schillok: {
    dex: 8, name: "Schillok", role: "Flutgarde", types: ["water"], sprite: "schiggy", evoTo: "turtok",
    recolor: { "#60a5fa": "#6366f1", "#2563eb": "#4338ca" }, scale: 1.12,
    base: [58, 20, 22, 10], grow: [4.4, 1.8, 1.9, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"tackle"],[1,"aquaknarre"],[1,"panzerschutz"],[1,"blubbstrahl"],[11,"hydropumpe"]],
  },
  bisasam: {
    dex: 1, name: "Bisasam", role: "Druide", types: ["grass","poison"], sprite: "bisasam",
    base: [42, 16, 14, 9], grow: [3.9, 1.7, 1.5, 0], mov: 3, jmp: 2,
    learn: [[1,"tackle"],[1,"rankenhieb"],[4,"megasauger"],[7,"schlafpuder"],[10,"rasierblatt"]],
    evoLvl: 10, evoTo: "bisaknosp",
  },
  bisaknosp: {
    dex: 2, name: "Bisaknosp", role: "Erzdruide", types: ["grass","poison"], sprite: "bisasam", evoTo: "bisaflor",
    recolor: { "#22c55e": "#ec4899", "#15803d": "#be185d", "#2dd4bf": "#0d9488" }, scale: 1.12,
    base: [56, 21, 18, 10], grow: [4.3, 1.9, 1.7, 0], mov: 3, jmp: 2,
    learn: [[1,"tackle"],[1,"rankenhieb"],[1,"megasauger"],[1,"schlafpuder"],[1,"rasierblatt"]],
  },
  evoli: {
    dex: 133, name: "Evoli", role: "Weißmagier", types: ["normal"], sprite: "evoli",
    base: [40, 14, 13, 11], grow: [3.7, 1.5, 1.4, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"heilwoge"],[5,"sternschauer"],[8,"heuler"],[11,"bodyslam"]],
  },
  machollo: {
    dex: 66, name: "Machollo", role: "Mönch", types: ["fighting"], sprite: "machollo",
    base: [46, 19, 14, 9], grow: [4.2, 2.0, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[4,"protzer"],[8,"geowurf"]],
    evoLvl: 11, evoTo: "maschock",
  },
  maschock: {
    dex: 67, name: "Maschock", role: "Großmeister", types: ["fighting"], sprite: "machollo", evoTo: "machomei",
    recolor: { "#94a3b8": "#a78bfa", "#64748b": "#7c3aed" }, scale: 1.12,
    base: [60, 25, 18, 9], grow: [4.6, 2.2, 1.7, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[1,"protzer"],[1,"geowurf"],[1,"bodyslam"]],
  },
  abra: {
    dex: 63, name: "Abra", role: "Mystiker", types: ["psychic"], sprite: "abra",
    base: [34, 18, 9, 12], grow: [3.2, 2.0, 1.0, 0], mov: 4, jmp: 3,
    learn: [[1,"konfusion"],[5,"barriere"],[8,"psystrahl"],[12,"genesung"]],
    evoLvl: 12, evoTo: "kadabra",
  },
  kadabra: {
    dex: 64, name: "Kadabra", role: "Erzmystiker", types: ["psychic"], sprite: "abra", evoTo: "simsala",
    recolor: { "#fde047": "#fbbf24", "#a16207": "#78350f" }, scale: 1.12,
    base: [44, 24, 12, 13], grow: [3.6, 2.2, 1.2, 0], mov: 4, jmp: 3,
    learn: [[1,"konfusion"],[1,"barriere"],[1,"psystrahl"],[1,"genesung"],[1,"psychokinese"]],
  },
  nebulak: {
    dex: 92, name: "Nebulak", role: "Schattendieb", types: ["ghost","poison"], sprite: "nebulak",
    base: [36, 18, 10, 12], grow: [3.4, 1.9, 1.1, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"schlecker"],[1,"nachtnebel"],[6,"hypnose"],[10,"spukball"]],
    evoLvl: 11, evoTo: "alpollo",
  },
  alpollo: {
    dex: 93, name: "Alpollo", role: "Phantom", types: ["ghost","poison"], sprite: "nebulak", evoTo: "gengar",
    recolor: { "#a78bfa": "#7c3aed", "#6d28d9": "#4c1d95" }, scale: 1.12,
    base: [48, 23, 13, 13], grow: [3.8, 2.1, 1.3, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"schlecker"],[1,"nachtnebel"],[1,"hypnose"],[1,"spukball"]],
  },
  kleinstein: {
    dex: 74, name: "Kleinstein", role: "Steinwächter", types: ["rock","ground"], sprite: "kleinstein",
    base: [44, 18, 20, 6], grow: [4.0, 1.9, 2.0, 0], mov: 3, jmp: 1,
    learn: [[1,"steinwurf"],[4,"haertner"],[8,"intensitaet"],[11,"steinhagel"]],
    evoLvl: 11, evoTo: "georok",
  },
  georok: {
    dex: 75, name: "Georok", role: "Felsbastion", types: ["rock","ground"], sprite: "kleinstein", evoTo: "geowaz",
    recolor: { "#a8a29e": "#78716c", "#78716c": "#44403c" }, scale: 1.18,
    base: [60, 23, 26, 6], grow: [4.4, 2.1, 2.2, 0], mov: 3, jmp: 1,
    learn: [[1,"steinwurf"],[1,"haertner"],[1,"intensitaet"],[1,"steinhagel"]],
  },
  relaxo: {
    dex: 143, name: "Relaxo", role: "Koloss", types: ["normal"], sprite: "relaxo",
    base: [70, 20, 18, 5], grow: [5.5, 2.0, 1.8, 0], mov: 3, jmp: 1,
    learn: [[1,"bodyslam"],[1,"erholung"],[1,"heuler"]],
  },

  /* === Dritte Entwicklungsstufen (V2.5) === */
  glurak: {
    dex: 6, name: "Glurak", role: "Himmelsdrache", types: ["fire","flying"], sprite: "glumanda",
    base: [66, 28, 20, 12], grow: [4.8, 2.3, 1.8, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"flammenwurf"],[1,"feuerwirbel"],[1,"fluegelschlag"],[1,"biss"]],
  },
  turtok: {
    dex: 9, name: "Turtok", role: "Panzerfestung", types: ["water"], sprite: "schiggy",
    base: [70, 24, 26, 10], grow: [5.0, 2.0, 2.2, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"hydropumpe"],[1,"blubbstrahl"],[1,"panzerschutz"],[1,"bodyslam"]],
  },
  bisaflor: {
    dex: 3, name: "Bisaflor", role: "Urwaldkoloss", types: ["grass","poison"], sprite: "bisasam",
    base: [68, 25, 22, 10], grow: [4.9, 2.1, 2.0, 0], mov: 3, jmp: 2,
    learn: [[1,"rasierblatt"],[1,"megasauger"],[1,"schlafpuder"],[1,"saeure"]],
  },
  simsala: {
    dex: 65, name: "Simsala", role: "Erzmagier", types: ["psychic"], sprite: "abra",
    base: [54, 30, 14, 14], grow: [4.0, 2.5, 1.4, 0], mov: 4, jmp: 3,
    learn: [[1,"psychokinese"],[1,"psystrahl"],[1,"barriere"],[1,"genesung"]],
  },
  machomei: {
    dex: 68, name: "Machomei", role: "Vier-Arm-Titan", types: ["fighting"], sprite: "machollo",
    base: [72, 30, 21, 9], grow: [5.2, 2.5, 1.9, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[1,"geowurf"],[1,"bodyslam"],[1,"protzer"]],
  },
  gengar: {
    dex: 94, name: "Gengar", role: "Schattenfürst", types: ["ghost","poison"], sprite: "nebulak",
    base: [58, 28, 16, 14], grow: [4.2, 2.4, 1.5, 0], mov: 5, jmp: 5, fly: true,
    learn: [[1,"spukball"],[1,"hypnose"],[1,"nachtnebel"],[1,"saeure"]],
  },
  geowaz: {
    dex: 76, name: "Geowaz", role: "Bergriese", types: ["rock","ground"], sprite: "kleinstein",
    base: [74, 27, 30, 7], grow: [5.2, 2.3, 2.5, 0], mov: 3, jmp: 1,
    learn: [[1,"steinhagel"],[1,"intensitaet"],[1,"geowurf"],[1,"haertner"]],
  },
  sarzenia: {
    dex: 71, name: "Sarzenia", role: "Fleischfresser", types: ["grass","poison"], sprite: "bisasam",
    base: [64, 28, 17, 11], grow: [4.7, 2.4, 1.6, 0], mov: 4, jmp: 2,
    learn: [[1,"rasierblatt"],[1,"saeure"],[1,"schlafpuder"],[1,"biss"]],
  },

  /* === Neue Spieler-Pokémon (Run-Vielfalt) === */
  fukano: {
    dex: 58, name: "Fukano", role: "Flammenwächter", types: ["fire"], sprite: "evoli",
    base: [40, 17, 12, 10], grow: [3.7, 1.8, 1.3, 0], mov: 4, jmp: 2,
    learn: [[1,"biss"],[1,"glut"],[4,"ruckzuck"],[8,"flammenwurf"]],
    evoTo: "arkani",
  },
  arkani: {
    dex: 59, name: "Arkani", role: "Legendenhund", types: ["fire"], sprite: "evoli",
    base: [56, 24, 16, 12], grow: [4.3, 2.1, 1.5, 0], mov: 5, jmp: 2,
    learn: [[1,"biss"],[1,"glut"],[1,"ruckzuck"],[1,"flammenwurf"]],
  },
  menki: {
    dex: 56, name: "Menki", role: "Raufbold", types: ["fighting"], sprite: "machollo",
    base: [40, 18, 11, 11], grow: [3.6, 1.9, 1.2, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[1,"ruckzuck"],[6,"protzer"],[9,"geowurf"]],
    evoTo: "rasaff",
  },
  rasaff: {
    dex: 57, name: "Rasaff", role: "Wutprimat", types: ["fighting"], sprite: "machollo",
    base: [54, 24, 15, 12], grow: [4.2, 2.2, 1.4, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[1,"geowurf"],[1,"protzer"],[1,"ruckzuck"]],
  },
  knofensa: {
    dex: 69, name: "Knofensa", role: "Schlingpflanze", types: ["grass","poison"], sprite: "bisasam",
    base: [38, 18, 10, 9], grow: [3.5, 2.0, 1.1, 0], mov: 3, jmp: 2,
    learn: [[1,"rankenhieb"],[1,"giftstachel"],[5,"schlafpuder"],[9,"rasierblatt"]],
    evoTo: "ultrigaria",
  },
  ultrigaria: {
    dex: 70, name: "Ultrigaria", role: "Würgranke", types: ["grass","poison"], sprite: "bisasam", evoTo: "sarzenia",
    base: [52, 24, 14, 10], grow: [4.1, 2.2, 1.3, 0], mov: 3, jmp: 2,
    learn: [[1,"rankenhieb"],[1,"saeure"],[1,"schlafpuder"],[1,"rasierblatt"]],
  },
  sterndu: {
    dex: 120, name: "Sterndu", role: "Seestern", types: ["water"], sprite: "kleinstein",
    base: [40, 15, 14, 10], grow: [3.7, 1.6, 1.5, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"tackle"],[1,"aquaknarre"],[5,"sternschauer"],[9,"blubbstrahl"]],
    evoTo: "starmie",
  },
  starmie: {
    dex: 121, name: "Starmie", role: "Sternjuwel", types: ["water","psychic"], sprite: "kleinstein",
    base: [52, 21, 18, 12], grow: [4.0, 1.9, 1.7, 0], mov: 4, jmp: 2, swim: true,
    learn: [[1,"aquaknarre"],[1,"sternschauer"],[1,"psystrahl"],[1,"genesung"]],
  },
  voltobal: {
    dex: 100, name: "Voltobal", role: "Kugelblitz", types: ["electric"], sprite: "kleinstein",
    base: [36, 15, 12, 12], grow: [3.4, 1.7, 1.3, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[1,"donnerschock"],[5,"donnerwelle"],[9,"funkensprung"]],
    evoTo: "lektrobal",
  },
  lektrobal: {
    dex: 101, name: "Lektrobal", role: "Gewitterkugel", types: ["electric"], sprite: "kleinstein",
    base: [48, 20, 16, 14], grow: [3.8, 1.9, 1.5, 0], mov: 5, jmp: 2,
    learn: [[1,"donnerschock"],[1,"donnerwelle"],[1,"funkensprung"],[1,"donnerblitz"]],
  },
  sleima: {
    dex: 88, name: "Sleima", role: "Schlammwesen", types: ["poison"], sprite: "relaxo",
    base: [44, 16, 13, 6], grow: [4.0, 1.8, 1.4, 0], mov: 3, jmp: 1,
    learn: [[1,"giftstachel"],[1,"schlecker"],[5,"saeure"],[9,"bodyslam"]],
    evoTo: "sleimok",
  },
  sleimok: {
    dex: 89, name: "Sleimok", role: "Schlammkoloss", types: ["poison"], sprite: "relaxo",
    base: [60, 22, 17, 7], grow: [4.6, 2.0, 1.6, 0], mov: 3, jmp: 1,
    learn: [[1,"giftstachel"],[1,"saeure"],[1,"bodyslam"],[1,"schlecker"]],
  },
  karpador: {
    dex: 129, name: "Karpador", role: "Hoffnungsträger", types: ["water"], sprite: "schiggy",
    base: [36, 8, 10, 11], grow: [3.0, 1.0, 1.1, 0], mov: 4, jmp: 2, swim: true,
    learn: [[1,"platscher"]],
    evoTo: "garados",
  },
  garados: {
    dex: 130, name: "Garados", role: "Schreckensdrache", types: ["water","flying"], sprite: "rettan",
    base: [62, 26, 17, 11], grow: [4.8, 2.3, 1.6, 0], mov: 4, jmp: 2, swim: true,
    learn: [[1,"biss"],[1,"aquaknarre"],[1,"hydropumpe"],[1,"intensitaet"]],
  },

  /* === Welle 3: viele neue Gefährten (Eis/Käfer/Drache & mehr) === */
  vulpix: {
    dex: 37, name: "Vulpix", role: "Fuchsglut", types: ["fire"], sprite: "glumanda",
    base: [36, 15, 13, 11], grow: [3.6, 1.7, 1.4, 0], mov: 4, jmp: 2,
    learn: [[1,"glut"],[1,"ruckzuck"],[5,"feuerwirbel"],[9,"flammenwurf"]],
    evoLvl: 9, evoTo: "vulnona",
  },
  vulnona: {
    dex: 38, name: "Vulnona", role: "Neunschweif", types: ["fire"], sprite: "glumanda",
    base: [52, 22, 18, 13], grow: [4.1, 2.0, 1.6, 0], mov: 4, jmp: 2,
    learn: [[1,"flammenwurf"],[1,"feuerwirbel"],[1,"sternschauer"]],
  },
  enton: {
    dex: 54, name: "Enton", role: "Migräne-Ente", types: ["water"], sprite: "schiggy",
    base: [40, 15, 13, 10], grow: [3.8, 1.7, 1.4, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"aquaknarre"],[1,"tackle"],[6,"konfusion"]],
    evoLvl: 10, evoTo: "entoron",
  },
  entoron: {
    dex: 55, name: "Entoron", role: "Sturzbach", types: ["water","psychic"], sprite: "schiggy",
    base: [56, 23, 18, 12], grow: [4.3, 2.0, 1.6, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"hydropumpe"],[1,"psystrahl"],[1,"aquaknarre"]],
  },
  quapsel: {
    dex: 60, name: "Quapsel", role: "Kaulquappe", types: ["water"], sprite: "schiggy",
    base: [38, 15, 12, 10], grow: [3.6, 1.7, 1.3, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"aquaknarre"],[1,"tackle"],[6,"karateschlag"]],
    evoLvl: 8, evoTo: "quaputzi",
  },
  quaputzi: {
    dex: 61, name: "Quaputzi", role: "Strudler", types: ["water"], sprite: "schiggy",
    base: [50, 20, 16, 11], grow: [4.0, 1.9, 1.5, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"aquaknarre"],[1,"karateschlag"],[10,"hydropumpe"]],
    evoLvl: 12, evoTo: "quappo",
  },
  quappo: {
    dex: 62, name: "Quappo", role: "Faustkämpfer", types: ["water","fighting"], sprite: "machollo",
    base: [64, 26, 19, 11], grow: [4.6, 2.2, 1.7, 0], mov: 4, jmp: 2, swim: true,
    learn: [[1,"hydropumpe"],[1,"geowurf"],[1,"karateschlag"],[1,"bodyslam"]],
  },
  ponita: {
    dex: 77, name: "Ponita", role: "Feuerfohlen", types: ["fire"], sprite: "glumanda",
    base: [40, 17, 13, 13], grow: [3.8, 1.9, 1.4, 0], mov: 5, jmp: 3,
    learn: [[1,"glut"],[1,"ruckzuck"],[7,"feuerwirbel"]],
    evoLvl: 10, evoTo: "gallopa",
  },
  gallopa: {
    dex: 78, name: "Gallopa", role: "Flammenross", types: ["fire"], sprite: "glumanda",
    base: [56, 24, 17, 15], grow: [4.3, 2.1, 1.6, 0], mov: 5, jmp: 3,
    learn: [[1,"flammenwurf"],[1,"feuerwirbel"],[1,"ruckzuck"]],
  },
  flegmon: {
    dex: 79, name: "Flegmon", role: "Tagträumer", types: ["water","psychic"], sprite: "relaxo",
    base: [52, 15, 15, 5], grow: [4.6, 1.6, 1.6, 0], mov: 3, jmp: 1, swim: true,
    learn: [[1,"aquaknarre"],[1,"konfusion"],[1,"genesung"]],
    evoLvl: 12, evoTo: "lahmus",
  },
  lahmus: {
    dex: 80, name: "Lahmus", role: "Muschelweiser", types: ["water","psychic"], sprite: "relaxo",
    base: [68, 22, 24, 6], grow: [5.0, 1.9, 2.1, 0], mov: 3, jmp: 1, swim: true,
    learn: [[1,"hydropumpe"],[1,"psychokinese"],[1,"genesung"],[1,"panzerschutz"]],
  },
  krabby: {
    dex: 98, name: "Krabby", role: "Zangentier", types: ["water"], sprite: "kleinstein",
    base: [36, 17, 16, 9], grow: [3.5, 1.9, 1.7, 0], mov: 3, jmp: 1, swim: true,
    learn: [[1,"aquaknarre"],[1,"steinwurf"],[1,"karateschlag"]],
    evoLvl: 10, evoTo: "kingler",
  },
  kingler: {
    dex: 99, name: "Kingler", role: "Scherenmeister", types: ["water"], sprite: "kleinstein",
    base: [54, 26, 22, 10], grow: [4.2, 2.3, 2.0, 0], mov: 3, jmp: 1, swim: true,
    learn: [[1,"hydropumpe"],[1,"steinhagel"],[1,"geowurf"]],
  },
  owei: {
    dex: 102, name: "Owei", role: "Eierbund", types: ["grass","psychic"], sprite: "bisasam",
    base: [44, 14, 14, 8], grow: [3.8, 1.6, 1.5, 0], mov: 3, jmp: 2,
    learn: [[1,"rankenhieb"],[1,"konfusion"],[6,"schlafpuder"]],
    evoLvl: 12, evoTo: "kokowei",
  },
  kokowei: {
    dex: 103, name: "Kokowei", role: "Palmwächter", types: ["grass","psychic"], sprite: "bisasam",
    base: [62, 24, 18, 9], grow: [4.5, 2.2, 1.7, 0], mov: 3, jmp: 2,
    learn: [[1,"rasierblatt"],[1,"psychokinese"],[1,"megasauger"]],
  },
  mauzi: {
    dex: 52, name: "Mauzi", role: "Katzendieb", types: ["normal"], sprite: "rattfratz",
    base: [36, 15, 11, 12], grow: [3.4, 1.6, 1.2, 0], mov: 4, jmp: 2,
    learn: [[1,"ruckzuck"],[1,"biss"],[6,"sternschauer"]],
    evoLvl: 10, evoTo: "snobilikat",
  },
  snobilikat: {
    dex: 53, name: "Snobilikat", role: "Edelkatze", types: ["normal"], sprite: "rattfratz",
    base: [52, 22, 16, 14], grow: [4.0, 2.0, 1.5, 0], mov: 5, jmp: 2,
    learn: [[1,"biss"],[1,"sternschauer"],[1,"bodyslam"]],
  },
  digda: {
    dex: 50, name: "Digda", role: "Maulwurf", types: ["ground"], sprite: "sandan",
    base: [30, 16, 9, 12], grow: [3.0, 1.8, 1.1, 0], mov: 4, jmp: 2,
    learn: [[1,"schaufler"],[1,"tackle"],[7,"intensitaet"]],
    evoLvl: 10, evoTo: "digdri",
  },
  digdri: {
    dex: 51, name: "Digdri", role: "Dreikopf-Gräber", types: ["ground"], sprite: "sandan",
    base: [44, 24, 14, 15], grow: [3.6, 2.2, 1.3, 0], mov: 5, jmp: 2,
    learn: [[1,"schaufler"],[1,"intensitaet"],[1,"steinhagel"]],
  },
  sichlor: {
    dex: 123, name: "Sichlor", role: "Sensenmeister", types: ["bug","flying"], sprite: "taubsi",
    base: [58, 26, 16, 14], grow: [4.4, 2.3, 1.5, 0], mov: 5, jmp: 4, fly: true,
    learn: [[1,"käfersäbel"],[1,"zornklinge"],[1,"fluegelschlag"],[1,"ruckzuck"]],
  },
  pinsir: {
    dex: 127, name: "Pinsir", role: "Zangenkäfer", types: ["bug"], sprite: "machollo",
    base: [60, 27, 20, 11], grow: [4.5, 2.4, 1.8, 0], mov: 4, jmp: 2,
    learn: [[1,"zornklinge"],[1,"käfersäbel"],[1,"geowurf"],[1,"steinwurf"]],
  },
  dratini: {
    dex: 147, name: "Dratini", role: "Mini-Drache", types: ["dragon"], sprite: "rettan",
    base: [40, 17, 12, 10], grow: [3.9, 1.9, 1.3, 0], mov: 4, jmp: 2, swim: true,
    learn: [[1,"drachenwut"],[1,"tackle"],[8,"aquaknarre"]],
    evoLvl: 10, evoTo: "dragonir",
  },
  dragonir: {
    dex: 148, name: "Dragonir", role: "Sturmdrache", types: ["dragon"], sprite: "rettan",
    base: [56, 23, 17, 12], grow: [4.5, 2.2, 1.6, 0], mov: 4, jmp: 3, swim: true,
    learn: [[1,"drachenklaue"],[1,"drachenwut"],[1,"eisstrahl"]],
    evoLvl: 16, evoTo: "dragoran",
  },
  dragoran: {
    dex: 149, name: "Dragoran", role: "Friedensdrache", types: ["dragon","flying"], sprite: "relaxo",
    base: [74, 29, 20, 12], grow: [5.0, 2.5, 1.8, 0], mov: 4, jmp: 4, fly: true,
    learn: [[1,"wutanfall"],[1,"drachenklaue"],[1,"flammenwurf"],[1,"fluegelschlag"]],
  },
  elektek: {
    dex: 125, name: "Elektek", role: "Stromfaust", types: ["electric"], sprite: "machollo",
    base: [56, 24, 16, 15], grow: [4.3, 2.2, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"donnerblitz"],[1,"donnerschock"],[1,"karateschlag"],[1,"funkensprung"]],
  },
  magmar: {
    dex: 126, name: "Magmar", role: "Lavafaust", types: ["fire"], sprite: "machollo",
    base: [58, 25, 17, 13], grow: [4.4, 2.3, 1.6, 0], mov: 4, jmp: 2,
    learn: [[1,"flammenwurf"],[1,"feuerwirbel"],[1,"karateschlag"]],
  },
  rossana: {
    dex: 124, name: "Rossana", role: "Eistänzerin", types: ["ice","psychic"], sprite: "abra",
    base: [56, 24, 18, 14], grow: [4.3, 2.2, 1.6, 0], mov: 4, jmp: 3,
    learn: [[1,"eisstrahl"],[1,"psychokinese"],[1,"schneesturm"],[1,"genesung"]],
  },
  lapras: {
    dex: 131, name: "Lapras", role: "Seeungeheuer", types: ["water","ice"], sprite: "relaxo",
    base: [78, 24, 20, 9], grow: [5.4, 2.1, 1.8, 0], mov: 3, jmp: 2, swim: true,
    learn: [[1,"hydropumpe"],[1,"eisstrahl"],[1,"schneesturm"],[1,"genesung"]],
  },
  aquana: {
    dex: 134, name: "Aquana", role: "Wassergeist", types: ["water"], sprite: "evoli",
    base: [68, 22, 19, 11], grow: [4.9, 2.0, 1.7, 0], mov: 4, jmp: 2, swim: true,
    learn: [[1,"hydropumpe"],[1,"aquaknarre"],[1,"aurorastrahl"]],
  },
  blitza: {
    dex: 135, name: "Blitza", role: "Donnergeist", types: ["electric"], sprite: "evoli",
    base: [58, 24, 16, 16], grow: [4.3, 2.2, 1.5, 0], mov: 5, jmp: 2,
    learn: [[1,"donnerblitz"],[1,"funkensprung"],[1,"ruckzuck"]],
  },
  flamara: {
    dex: 136, name: "Flamara", role: "Flammengeist", types: ["fire"], sprite: "evoli",
    base: [60, 27, 16, 13], grow: [4.4, 2.4, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"flammenwurf"],[1,"feuerwirbel"],[1,"biss"]],
  },
  chaneira: {
    dex: 113, name: "Chaneira", role: "Glückspflegerin", types: ["normal"], sprite: "relaxo",
    base: [90, 10, 12, 8], grow: [5.8, 1.2, 1.4, 0], mov: 3, jmp: 1,
    learn: [[1,"sternschauer"],[1,"heilwoge"],[1,"genesung"],[1,"barriere"]],
  },
  tauros: {
    dex: 128, name: "Tauros", role: "Wildstier", types: ["normal"], sprite: "rattfratz",
    base: [62, 26, 19, 14], grow: [4.6, 2.3, 1.7, 0], mov: 5, jmp: 2,
    learn: [[1,"bodyslam"],[1,"geowurf"],[1,"biss"],[1,"intensitaet"]],
  },
  kicklee: {
    dex: 106, name: "Kicklee", role: "Tritt-Akrobat", types: ["fighting"], sprite: "machollo",
    base: [54, 26, 15, 13], grow: [4.2, 2.4, 1.4, 0], mov: 4, jmp: 3,
    learn: [[1,"karateschlag"],[1,"geowurf"],[1,"protzer"]],
  },
  nockchan: {
    dex: 107, name: "Nockchan", role: "Box-Champ", types: ["fighting"], sprite: "machollo",
    base: [54, 25, 17, 12], grow: [4.2, 2.3, 1.6, 0], mov: 4, jmp: 2,
    learn: [[1,"karateschlag"],[1,"bodyslam"],[1,"protzer"]],
  },
  arktos: {
    dex: 144, name: "Arktos", role: "Eisschwinge", types: ["ice","flying"], sprite: "taubsi",
    base: [78, 27, 20, 13], grow: [5.2, 2.4, 1.8, 0], mov: 5, jmp: 5, fly: true,
    learn: [[1,"eisstrahl"],[1,"schneesturm"],[1,"fluegelschlag"],[1,"aurorastrahl"]],
  },
  zapdos: {
    dex: 145, name: "Zapdos", role: "Gewittervogel", types: ["electric","flying"], sprite: "taubsi",
    base: [78, 28, 18, 15], grow: [5.2, 2.5, 1.7, 0], mov: 5, jmp: 5, fly: true,
    learn: [[1,"donnerblitz"],[1,"funkensprung"],[1,"fluegelschlag"]],
  },
  lavados: {
    dex: 146, name: "Lavados", role: "Flammenphönix", types: ["fire","flying"], sprite: "taubsi",
    base: [78, 29, 18, 14], grow: [5.2, 2.6, 1.7, 0], mov: 5, jmp: 5, fly: true,
    learn: [[1,"flammenwurf"],[1,"feuerwirbel"],[1,"fluegelschlag"]],
  },

  /* === Gegner === */
  habitak: {
    dex: 21, name: "Habitak", role: "Sturzflieger", types: ["normal","flying"], sprite: "taubsi",
    base: [30, 14, 9, 12], grow: [2.9, 1.5, 1.0, 0], mov: 4, jmp: 4, fly: true,
    learn: [[1,"schnabel"],[3,"windstoss"],[6,"fluegelschlag"]],
  },
  smettbo: {
    dex: 12, name: "Smettbo", role: "Puderflügel", types: ["flying","poison"], sprite: "zubat",
    base: [34, 15, 11, 10], grow: [3.1, 1.6, 1.1, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"windstoss"],[4,"schlafpuder"],[8,"psystrahl"]],
  },
  golbat: {
    dex: 42, name: "Golbat", role: "Schattenflügel", types: ["poison","flying"], sprite: "zubat",
    base: [44, 19, 13, 13], grow: [3.6, 1.9, 1.3, 0], mov: 5, jmp: 5, fly: true,
    learn: [[1,"biss"],[1,"giftstachel"],[1,"superschall"],[1,"fluegelschlag"]],
  },

  rattfratz: {
    dex: 19, name: "Rattfratz", role: "Plünderer", types: ["normal"], sprite: "rattfratz",
    base: [32, 14, 10, 10], grow: [3.0, 1.5, 1.1, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[3,"biss"],[6,"ruckzuck"]],
  },
  taubsi: {
    dex: 16, name: "Taubsi", role: "Späher", types: ["normal","flying"], sprite: "taubsi",
    base: [32, 13, 10, 11], grow: [3.0, 1.4, 1.1, 0], mov: 4, jmp: 4, fly: true,
    learn: [[1,"schnabel"],[3,"windstoss"],[7,"fluegelschlag"]],
  },
  zubat: {
    dex: 41, name: "Zubat", role: "Nachtjäger", types: ["poison","flying"], sprite: "zubat",
    base: [30, 14, 9, 12], grow: [2.9, 1.5, 1.0, 0], mov: 4, jmp: 5, fly: true,
    learn: [[1,"biss"],[3,"superschall"],[6,"giftstachel"]],
  },
  rettan: {
    dex: 23, name: "Rettan", role: "Giftklinge", types: ["poison"], sprite: "rettan",
    base: [34, 15, 11, 9], grow: [3.2, 1.6, 1.2, 0], mov: 4, jmp: 2,
    learn: [[1,"giftstachel"],[4,"biss"],[7,"saeure"]],
  },
  sandan: {
    dex: 27, name: "Sandan", role: "Wüstenkrieger", types: ["ground"], sprite: "sandan",
    base: [38, 16, 14, 8], grow: [3.5, 1.7, 1.5, 0], mov: 4, jmp: 2,
    learn: [[1,"tackle"],[4,"schaufler"],[8,"intensitaet"]],
  },
  tragosso: {
    dex: 104, name: "Tragosso", role: "Knochenwache", types: ["ground"], sprite: "tragosso",
    base: [40, 17, 15, 7], grow: [3.6, 1.8, 1.6, 0], mov: 3, jmp: 2,
    learn: [[1,"knochenkeule"],[5,"knochmerang"]],
  },
  magnetilo: {
    dex: 81, name: "Magnetilo", role: "Wachdrohne", types: ["electric"], sprite: "magnetilo",
    base: [34, 16, 14, 8], grow: [3.2, 1.7, 1.5, 0], mov: 3, jmp: 4, fly: true,
    learn: [[1,"donnerschock"],[5,"donnerwelle"],[9,"funkensprung"]],
  },
  onix: {
    dex: 95, name: "Onix", role: "Felskoloss", types: ["rock","ground"], sprite: "onix",
    base: [62, 18, 24, 6], grow: [5.0, 1.9, 2.2, 0], mov: 3, jmp: 2, boss: true,
    learn: [[1,"steinwurf"],[1,"tackle"],[6,"steinhagel"],[10,"intensitaet"]],
  },
  mewtu: {
    dex: 150, name: "Mewtu", role: "Champion", types: ["psychic"], sprite: "mewtu",
    base: [80, 23, 17, 13], grow: [5.0, 2.2, 1.7, 0], mov: 4, jmp: 3, boss: true,
    learn: [[1,"psystrahl"],[1,"psychoklinge"],[1,"genesung"],[1,"barriere"]],
  },
};

/* ---------- Pixel-Sprites (16×16) ----------
   '.' = transparent, 'k' = Kontur. Jedes Sprite: { pal, px } */
const SPRITES = {
  pikachu: {
    pal: { k:"#222034", y:"#ffcb05", o:"#f59e0b", r:"#ef4444", w:"#ffffff", n:"#b45309" },
    px: [
      "..k..........k..",
      ".kkk........kkk.",
      ".kykk......kkyk.",
      "..kykk....kkyk..",
      "..kyykkkkkkyyk..",
      "..kyyyyyyyyyyk..",
      ".kyykyyyyykyyk..",
      ".kyykyyyyykyyk..",
      ".kyryyyyyyyryk..",
      ".kyryyykkyyryk..",
      "..kyyyyyyyyyk...",
      "..kyyyyyyyyykkk.",
      ".kyyyyyyyyyknnk.",
      ".kyykyyyykyyknk.",
      ".kyykyyyykyykk..",
      "..kk..kk..kk....",
    ],
  },
  glumanda: {
    pal: { k:"#222034", o:"#fb923c", O:"#ea580c", c:"#fde68a", r:"#ef4444", f:"#fbbf24" },
    px: [
      "......kkkk......",
      ".....koooook....",
      "....koooooook...",
      "....kokoookok...",
      "....koooooook...",
      "....kookkoook...",
      ".....koooook....",
      "......koook..f..",
      ".....kooooookfk.",
      "....koocccookrk.",
      "...kooccccookk..",
      "...kooccccook...",
      "...kooccccook...",
      "....kooooook....",
      "....kok..kok....",
      ".....k....k.....",
    ],
  },
  schiggy: {
    pal: { k:"#222034", b:"#60a5fa", B:"#2563eb", s:"#fde68a", n:"#b45309" },
    px: [
      "......kkkk......",
      ".....kbbbbk.....",
      "....kbbbbbbk....",
      "...kbkbbbbkbk...",
      "...kbbbbbbbbk...",
      "...kbbkkkkbbk...",
      "....kbbbbbbk....",
      ".....kbbbbk.....",
      "....knnnnnnk....",
      "...knnssssnnk...",
      "..kbknssssknbk..",
      "..kbknssssknbk..",
      "...kknssssnkk...",
      "....knnnnnnk....",
      "....kbk..kbk....",
      ".....k....k.....",
    ],
  },
  bisasam: {
    pal: { k:"#222034", t:"#2dd4bf", T:"#0d9488", g:"#22c55e", G:"#15803d", r:"#ef4444" },
    px: [
      "......kkkk......",
      ".....kgGGgk.....",
      "....kgggggGk....",
      "...kgGgggGggk...",
      "...kGgggggGgk...",
      "....kgggggGk....",
      "..kkkkggggkkkk..",
      ".kttttkkkkttttk.",
      "ktttkttttttktttk",
      "kttkttttttttkttk",
      "kttkttkkkkttkttk",
      ".kttttttttttttk.",
      "..kttkttttkttk..",
      "..kttkttttkttk..",
      "...kk.kttk.kk...",
      ".......kk.......",
    ],
  },
  evoli: {
    pal: { k:"#222034", n:"#d97706", N:"#92400e", c:"#fef3c7" },
    px: [
      "..kk........kk..",
      ".knnk......knnk.",
      ".knNnk....knNnk.",
      ".knnnk....knnnk.",
      "..knnkkkkkknnk..",
      "..knnnnnnnnnnk..",
      ".knnknnnnnnknnk.",
      ".knnknnnnnnknnk.",
      ".knnnnnkknnnnnk.",
      "..knnnnnnnnnnk..",
      "...kncccccnnk...",
      "..knccccccnkkk..",
      "..knncccccnkNNk.",
      "..knnkcccknnkNk.",
      "..knnkcccknnkk..",
      "...kk.kk..kk....",
    ],
  },
  machollo: {
    pal: { k:"#222034", u:"#94a3b8", U:"#64748b" },
    px: [
      "....kkkkkkk.....",
      "...kuUUUUUuk....",
      "...kuuuuuuuk....",
      "...kukuuukuk....",
      "...kuuuuuuuk....",
      "...kuukkkuuk....",
      "....kuuuuuk.....",
      "..kkkuuuuukkk...",
      ".kuukuuuuukuuk..",
      ".kuukuuuuukuuk..",
      ".kuukuuuuukuuk..",
      "..kk.kuuuk.kk...",
      ".....kuuuk......",
      "....kuukuuk.....",
      "....kuukuuk.....",
      ".....kk.kk......",
    ],
  },
  abra: {
    pal: { k:"#222034", y:"#fde047", n:"#a16207" },
    px: [
      "...kk......kk...",
      "..kyyk....kyyk..",
      "..kyyyk..kyyyk..",
      "...kyyykkyyyk...",
      "...kyyyyyyyyk...",
      "...kykkyykkyk...",
      "...kyyyyyyyyk...",
      "....kyykkyyk....",
      ".....knnnnk.....",
      "....knnnnnnk....",
      "...kynnnnnnyk...",
      "..kyyknnnnkyyk..",
      "..kyyknnnnkyyk..",
      "...kkknnnnkkk...",
      ".....knk.knk....",
      "......k...k.....",
    ],
  },
  nebulak: {
    pal: { k:"#222034", v:"#a78bfa", V:"#6d28d9", w:"#ffffff" },
    px: [
      "....kk.kk.kk....",
      "...kvvkvvkvvk...",
      "..kvvvvvvvvvvk..",
      ".kvvVvvvvvvVvvk.",
      ".kvvvvvvvvvvvvk.",
      "kvvkwwkvvkwwkvvk",
      "kvvkwkkvvkwkkvvk",
      "kvvvvvvvvvvvvvvk",
      "kvvvvkkkkkkvvvvk",
      ".kvvvkwwwwkvvvk.",
      ".kvvvvkkkkvvvvk.",
      "..kvvvvvvvvvvk..",
      "...kvvkvvkvvk...",
      "....kk.kk.kk....",
      "................",
      "................",
    ],
  },
  kleinstein: {
    pal: { k:"#222034", s:"#a8a29e", S:"#78716c" },
    px: [
      "................",
      "....kkkkkkkk....",
      "...kssSssssSk...",
      "..kssssssssssk..",
      ".kSsskssskssssk.",
      ".kssskssskssssk.",
      "kssssssssssssssk",
      "ksksssskkssssksk",
      "kskssskssksskssk",
      "kssksssssssskssk",
      ".kskssskksssksk.",
      ".kkssssssssssкk.".replace("к","k"),
      "..kSssssssssSk..",
      "...kssssssssk...",
      "....kkkkkkkk....",
      "................",
    ],
  },
  relaxo: {
    pal: { k:"#222034", t:"#0f766e", T:"#134e4a", c:"#fef3c7" },
    px: [
      "...kk......kk...",
      "..kttkkkkkkttk..",
      "..kttttttttttk..",
      ".kttkttttttkttk.",
      ".kttttkkkkttttk.",
      ".ktttccccccttk..",
      ".kttccccccccttk.",
      "kttkccccccccкttk".replace("к","k"),
      "kttkccccccccкttk".replace("к","k"),
      "kttccccccccccttk",
      "kttccccccccccttk",
      ".kttccccccccttk.",
      ".kttkccccccкttk.".replace("к","k"),
      "..kkkccccccкkk..".replace("к","k"),
      "....kck..kck....",
      ".....k....k.....",
    ],
  },
  rattfratz: {
    pal: { k:"#222034", p:"#c084fc", P:"#7e22ce", c:"#fef3c7" },
    px: [
      "..kk........kk..",
      ".kppk......kppk.",
      ".kpPpk....kpPpk.",
      "..kppkkkkkkppk..",
      "..kppppppppppk..",
      ".kppkppppppkppk.",
      ".kppkppppppkppk.",
      ".kpppppkkpppppk.",
      "..kppppppppppk..",
      "...kpcccccppk...",
      "..kpcccccccpk...",
      "..kpcccccccpkkkk",
      "..kppcccccppk..k",
      "..kppkccckppk...",
      "...kk.kk..kk....",
      "................",
    ],
  },
  taubsi: {
    pal: { k:"#222034", n:"#d6a35c", N:"#9a6b2f", c:"#fef3c7", o:"#f97316" },
    px: [
      "......kkkk......",
      ".....knnnnk.....",
      "....knnnnnnk....",
      "...kNknnnnknk...",
      "...knnnnnnnnk...",
      "...knnnkkoook...",
      "....knnnnkok....",
      "..kkknnnnnkk....",
      ".kNNkncccnkNNk..",
      "kNNNkncccnkNNNk.",
      "kNNkncccccnkNNk.",
      ".kkncccccccnkk..",
      "..knncccccnnk...",
      "...knnnnnnnk....",
      "....kok.kok.....",
      ".....k...k......",
    ],
  },
  zubat: {
    pal: { k:"#222034", b:"#60a5fa", B:"#1d4ed8", m:"#a78bfa", w:"#ffffff" },
    px: [
      "kk............kk",
      "kBk..........kBk",
      "kBBk.kk..kk.kBBk",
      "kBBBkbbkkbbkBBBk",
      "kBBbbbbbbbbbbBBk",
      "kBbbbbbbbbbbbbBk",
      ".kBbbkbbbbkbbBk.",
      ".kBbbbbbbbbbbBk.",
      "..kBbbkmmkbbBk..",
      "..kBbbmmmmbbBk..",
      "...kBbkmmkbBk...",
      "...kBbbbbbbBk...",
      "....kkbbbbkk....",
      ".....kb..bk.....",
      ".....k....k.....",
      "................",
    ],
  },
  rettan: {
    pal: { k:"#222034", p:"#c084fc", P:"#7e22ce", y:"#fde047" },
    px: [
      "....kkkkk.......",
      "...kpppppk......",
      "..kppkppkpk.....",
      "..kpppppppk.....",
      "..kppkkkppk.....",
      "...kpyyypk......",
      "....kpppk.......",
      ".....kpppk......",
      "......kpppk.....",
      ".......kpppkkk..",
      "....kkkkpppppPk.",
      "...kPpppppppPPk.",
      "..kPpppkkkppPk..",
      "..kPppk...kkk...",
      "...kkk..........",
      "................",
    ],
  },
  sandan: {
    pal: { k:"#222034", y:"#facc15", Y:"#a16207", c:"#fef3c7" },
    px: [
      "...kk....kk.....",
      "..kyYk..kYyk....",
      "..kyyykkyyyk....",
      "..kyyyyyyyyk....",
      ".kyykyyyykyyk...",
      ".kyyyyyyyyyyk...",
      ".kyyykkkyyyyk...",
      "..kyyyyyyyykk...",
      "..kYyccccyykYk..",
      ".kYyccccccyykYk.",
      ".kYyccccccyykk..",
      ".kYyccccccyyk...",
      "..kycccccyyk....",
      "..kyykccckyyk...",
      "...kk.kk..kk....",
      "................",
    ],
  },
  tragosso: {
    pal: { k:"#222034", c:"#e7e5e4", C:"#a8a29e", n:"#d6a35c", N:"#9a6b2f" },
    px: [
      "....kkkkkkk.....",
      "...kcccccccк....".replace("к","k"),
      "..kccCcccCcck...",
      "..kccccccccck...",
      ".kcckccccкcccк..".replace(/к/g,"k"),
      ".kcckkccckkcck..",
      ".kcccccccccccк..".replace("к","k"),
      "..kccckkkcccк...".replace("к","k"),
      "...kknnnnnkk....",
      "...knnnnnnnk..kk",
      "..knnknnnknnkkck",
      "..knnnnnnnnnkck.",
      "..knnknnnknnck..",
      "...kk.knk.kk....",
      "......kkk.......",
      "................",
    ],
  },
  magnetilo: {
    pal: { k:"#222034", s:"#cbd5e1", S:"#64748b", r:"#ef4444", b:"#3b82f6", w:"#ffffff" },
    px: [
      "kk............kk",
      "krk....kk....kbk",
      "krk...kssk...kbk",
      "krkkkkssssкkkbk.".replace("к","k"),
      "krrrkssssssкbbbk".replace("к","k"),
      "kkkkssssssssкkkk".replace("к","k"),
      "...ksskwwkssk...",
      "...ksskwkkssk...",
      "...ksssкksssk...".replace("к","k"),
      "....kssssssk....",
      ".....kssssk.....",
      "....kkSSSSкk....".replace("к","k"),
      "....kSkkkkSk....",
      ".....k....k.....",
      "................",
      "................",
    ],
  },
  onix: {
    pal: { k:"#222034", s:"#9ca3af", S:"#4b5563" },
    px: [
      "....kkkkkk......",
      "...kssssssk.....",
      "..kskssskssk....",
      ".kssssssssssk...",
      ".kssкkkкssssk...".replace(/к/g,"k"),
      ".kssssssssssk...",
      "..ksskkkkssk....",
      "...kssssssk.....",
      "....kSSSSSSk....",
      "...kSSSSSSSSk...",
      "..kSSSkSSкSSSk..".replace("к","k"),
      "..kSSSSSSSSSSk..",
      ".kSSSSkSSkSSSSk.",
      ".kSSSSSSSSSSSSk.",
      "..kkkkkkkkkkkk..",
      "................",
    ],
  },
  mewtu: {
    pal: { k:"#222034", g:"#e2d9f3", G:"#b8a6d9", v:"#7c3aed" },
    px: [
      "..kk........kk..",
      ".kggk......kggk.",
      ".kgggkkkkkkgggk.",
      "..kgggggggggk...",
      "..kgkggggkggk...",
      "..kgvggggvggk...",
      "..kggggggggk....",
      "...kggkkggk.....",
      "....kggggk..kkk.",
      "...kggggggkkvvk.",
      "..kggkggggkvvk..",
      "..kggkggggvvk...",
      "..kggkggggk.....",
      "...kkgggggk.....",
      "....kgk.kgk.....",
      ".....k...k......",
    ],
  },
};

/* ---------- Gelände ----------
   img: Kenney-Tile (CC0, kenney.nl) in assets/tiles/
   side/side2: Sockel-Farben unter dem Tile-Bild (aus dem Bild gesampelt) */
const TERRAIN = {
  g: { name: "Gras",         img: "grass",     top: "#8cb846", top2: "#7ca340", side: "#7ca340", side2: "#5f7e30" },
  G: { name: "Dichtes Gras", img: "grassdark", top: "#659634", top2: "#59852e", side: "#59852e", side2: "#446722" },
  d: { name: "Erde",         img: "dirt",      top: "#ba8c5d", top2: "#a77d53", side: "#a77d53", side2: "#81603e" },
  s: { name: "Stein",        img: "stone",     top: "#8d8d8d", top2: "#7e7e7e", side: "#e1a567", side2: "#ae7e4d" },
  S: { name: "Fels",         img: "rock",      top: "#696969", top2: "#5e5e5e", side: "#a77d53", side2: "#81603e" },
  w: { name: "Wasser",       img: "water",     top: "#9cd4e2", top2: "#8cc6d6", side: "#a77d53", side2: "#81603e", water: true },
  b: { name: "Steg",         img: "bridge",    top: "#cfcabb", top2: "#bfb9a8", side: "#a77d53", side2: "#81603e" },
  p: { name: "Spukstein",    img: "ghost",     top: "#8369b8", top2: "#755da8", side: "#d08391", side2: "#a1646c" },
  P: { name: "Dunkelstein",  img: "ghostdark", top: "#594a78", top2: "#4d3f68", side: "#8d556b", side2: "#6d4150" },
  /* Hindernisse (block) & begehbare Deko: Boden-Tile + animiertes Overlay */
  t: { name: "Baum",         img: "grass", decor: "tree",    block: true, top: "#8cb846", top2: "#7ca340", side: "#7ca340", side2: "#5f7e30" },
  u: { name: "Buschwerk",    img: "grass", decor: "bush",    top: "#8cb846", top2: "#7ca340", side: "#7ca340", side2: "#5f7e30" },
  r: { name: "Felsbrocken",  img: "dirt",  decor: "boulder", block: true, top: "#ba8c5d", top2: "#a77d53", side: "#a77d53", side2: "#81603e" },
  c: { name: "Spukkristall", img: "ghost", decor: "crystal", block: true, top: "#8369b8", top2: "#755da8", side: "#d08391", side2: "#a1646c" },
};

/* ---------- Schlachten ---------- */
const BATTLES = [
  {
    id: 0, name: "Grüne Ebene", icon: "🌿", ambient: "meadow",
    desc: "Wilde Pokémon versperren den Weg. Ein sanfter Einstieg.",
    intro: "Wilde Pokémon greifen an!\nBesiege alle Gegner.",
    partySize: 4,
    heights: [
      "001111000",
      "001122100",
      "000122100",
      "000111100",
      "000011000",
      "000000000",
      "000000011",
      "000000111",
      "000000111",
    ],
    terrain: [
      "tgggggggt",
      "ggGGgggdg",
      "tgGGggddg",
      "gggggggdg",
      "ggggugggg",
      "gGgggggug",
      "gggggtgGG",
      "ggdddggGG",
      "ggdddgggG",
    ],
    spawns: [[1,7],[2,8],[1,6],[3,8]],
    enemies: [
      { sp: "rattfratz", lvl: 2, x: 6, y: 1 },
      { sp: "rattfratz", lvl: 2, x: 4, y: 2 },
      { sp: "taubsi",    lvl: 2, x: 7, y: 3 },
    ],
    exp: 90, recruit: { sp: "machollo", lvl: 3 },
  },
  {
    id: 1, name: "Flussfurt", icon: "🌊", ambient: "river",
    desc: "Ein reißender Fluss – nur die Brücke führt hinüber.",
    intro: "Gegner lauern am anderen Ufer.\nWasser-Pokémon können schwimmen!",
    partySize: 4,
    heights: [
      "1100000011",
      "1100000011",
      "0000000001",
      "0000000000",
      "0000110000",
      "0000000000",
      "0000000011",
      "1000000011",
      "1100000111",
    ],
    terrain: [
      "tgggwwgggt",
      "ggugwwgggg",
      "gGggwwggGg",
      "ggggwwgggg",
      "ggggbbgggg",
      "ggggwwgggg",
      "gguGwwgggg",
      "ggggwwggGg",
      "tgggwwgggt",
    ],
    spawns: [[1,3],[1,5],[2,4],[0,4]],
    enemies: [
      { sp: "taubsi", lvl: 3, x: 7, y: 2 },
      { sp: "rettan", lvl: 3, x: 8, y: 4 },
      { sp: "zubat",  lvl: 3, x: 7, y: 6 },
      { sp: "rattfratz", lvl: 3, x: 8, y: 5 },
    ],
    exp: 110, recruit: { sp: "abra", lvl: 4 },
  },
  {
    id: 2, name: "Felsschlucht", icon: "⛰", ambient: "canyon",
    desc: "Steile Klippen – wer oben steht, hat den Vorteil.",
    intro: "Die Gegner halten die Höhen besetzt.\nErobere die Schlucht!",
    partySize: 4,
    heights: [
      "3332100123",
      "3322100123",
      "2221000122",
      "1110000011",
      "0000000000",
      "1100000011",
      "2210000122",
      "3321001223",
      "3332101233",
    ],
    terrain: [
      "ssssddssss",
      "ssssddssss",
      "sssdddssss",
      "sdddddddss",
      "rddddddddr",
      "sdddddddds",
      "ssddddddss",
      "ssssdddsss",
      "ssssddssss",
    ],
    spawns: [[4,8],[5,8],[3,8],[6,8],[4,7]],
    enemies: [
      { sp: "sandan",   lvl: 4, x: 2, y: 1 },
      { sp: "tragosso", lvl: 4, x: 7, y: 1 },
      { sp: "rettan",   lvl: 4, x: 4, y: 2 },
      { sp: "sandan",   lvl: 4, x: 5, y: 1 },
      { sp: "tragosso", lvl: 5, x: 5, y: 0 },
    ],
    exp: 130, recruit: { sp: "evoli", lvl: 5 },
  },
  {
    id: 3, name: "Spukturm", icon: "👻", ambient: "ghost",
    desc: "Im alten Turm flackern unheimliche Lichter.",
    intro: "Geister-Pokémon erscheinen!\nNormale Hiebe verpuffen an ihnen …",
    partySize: 5,
    heights: [
      "011001100",
      "112112110",
      "122222210",
      "012333210",
      "012343210",
      "012333210",
      "012222210",
      "011111110",
      "000000000",
    ],
    terrain: [
      "cPPpppPPp",
      "pppppppPp",
      "pPpppppPp",
      "ppppPpppp",
      "pPppppppP",
      "ppppPpppp",
      "pPpppppPp",
      "cpppppppc",
      "PppPpppPP",
    ],
    spawns: [[3,8],[5,8],[4,8],[2,8],[6,8]],
    enemies: [
      { sp: "nebulak", lvl: 5, x: 3, y: 3 },
      { sp: "nebulak", lvl: 5, x: 5, y: 3 },
      { sp: "zubat",   lvl: 5, x: 1, y: 2 },
      { sp: "zubat",   lvl: 5, x: 7, y: 2 },
      { sp: "nebulak", lvl: 6, x: 4, y: 4, boss: true },
    ],
    exp: 150, recruit: { sp: "nebulak", lvl: 7 },
  },
  {
    id: 4, name: "Donnerplateau", icon: "⚡", ambient: "storm",
    desc: "Magnetische Wachdrohnen patrouillieren auf den Terrassen.",
    intro: "Die Drohnen schweben über jede Klippe.\nVorsicht vor Paralyse!",
    partySize: 5,
    heights: [
      "2223333222",
      "2223333222",
      "1122222211",
      "1111221111",
      "0011111100",
      "0000110000",
      "0000000000",
      "0000000000",
      "1100000011",
    ],
    terrain: [
      "ssssSSssss",
      "ssssSSssss",
      "rsssssssds",
      "ddssssssdd",
      "dddssssddd",
      "ddddssdddd",
      "dddddddddd",
      "gddddddddg",
      "rgddddddgr",
    ],
    spawns: [[3,8],[6,8],[4,8],[5,8],[2,8]],
    enemies: [
      { sp: "magnetilo", lvl: 6, x: 2, y: 2 },
      { sp: "magnetilo", lvl: 6, x: 7, y: 2 },
      { sp: "magnetilo", lvl: 6, x: 4, y: 1 },
      { sp: "tragosso",  lvl: 7, x: 5, y: 2 },
      { sp: "onix",      lvl: 7, x: 5, y: 0, boss: true },
    ],
    exp: 170, recruit: { sp: "kleinstein", lvl: 8 },
  },
  {
    id: 5, name: "Arena der Rivalen", icon: "⚔", ambient: "arena",
    desc: "Das Rivalen-Team fordert dich zum Duell.",
    intro: "Ein ebenbürtiges Team!\nSie kennen dieselben Tricks wie du.",
    partySize: 5,
    heights: [
      "311111113",
      "111111111",
      "111222111",
      "112222211",
      "112232211",
      "112222211",
      "111222111",
      "111111111",
      "311111113",
    ],
    terrain: [
      "Sssssssss",
      "sssssssss",
      "ssGGGGGss",
      "ssGgggGss",
      "ssGgggGss",
      "ssGgggGss",
      "ssGGGGGss",
      "sssssssss",
      "SssssssSS",
    ],
    spawns: [[3,8],[5,8],[4,8],[2,8],[6,8]],
    enemies: [
      { sp: "glutexo",  lvl: 8,  x: 4, y: 0, boss: true },
      { sp: "schillok", lvl: 8,  x: 2, y: 0 },
      { sp: "bisaknosp",lvl: 8,  x: 6, y: 0 },
      { sp: "raichu",   lvl: 8,  x: 4, y: 1 },
    ],
    exp: 200, recruit: { sp: "relaxo", lvl: 9 },
  },
  {
    id: 6, name: "Zitadelle des Champions", icon: "👑", ambient: "citadel", finale: true,
    desc: "Auf dem höchsten Thron wartet Mewtu.",
    intro: "Mewtu erhebt sich.\n»Zeigt mir eure Stärke – oder zerbrecht.«",
    partySize: 5,
    heights: [
      "2211111122",
      "2111111112",
      "1112222111",
      "1123333211",
      "1123443211",
      "1123333211",
      "1112222111",
      "1111111111",
      "0000000000",
    ],
    terrain: [
      "cPppppppPc",
      "PppppppppP",
      "pppPPPPppp",
      "ppPsssssPp",
      "ppPssssspP",
      "ppPsssssPp",
      "pppPPPPppp",
      "pppppppppp",
      "cppppppppc",
    ],
    spawns: [[3,8],[6,8],[4,8],[5,8],[2,8]],
    enemies: [
      { sp: "kadabra", lvl: 8, x: 2, y: 3 },
      { sp: "alpollo", lvl: 8, x: 7, y: 3 },
      { sp: "onix",    lvl: 8, x: 4, y: 2 },
      { sp: "magnetilo", lvl: 8, x: 5, y: 2 },
      { sp: "mewtu",   lvl: 10, x: 4, y: 4, boss: true },
    ],
    exp: 250,
  },

  /* ===== Karten-Varianten (werden pro Run gegen die Originale gewürfelt) ===== */
  {
    id: 7, name: "Blumenwiese", icon: "🌼", ambient: "meadow",
    desc: "Ein Meer aus Blüten – und frecher Flugschar.",
    intro: "Zwischen den Blumen raschelt es!\nBesiege alle Gegner.",
    partySize: 4,
    heights: [
      "000000000",
      "011000110",
      "011000110",
      "000000000",
      "000111000",
      "000111000",
      "000000000",
      "110000000",
      "110000000",
    ],
    terrain: [
      "tgggggggt",
      "ggggggggg",
      "gguGGuggg",
      "ggggggggg",
      "ggGuuuGgg",
      "ggGuuuGgg",
      "ggggggggg",
      "ggggggggg",
      "tgggggggt",
    ],
    spawns: [[1,7],[3,8],[2,8],[1,6],[4,8]],
    enemies: [
      { sp: "rattfratz", lvl: 2, x: 6, y: 1 },
      { sp: "habitak",   lvl: 2, x: 4, y: 1 },
      { sp: "smettbo",   lvl: 3, x: 7, y: 2 },
    ],
  },
  {
    id: 8, name: "Sumpfpfad", icon: "🐸", ambient: "river",
    desc: "Trübe Tümpel und giftiges Gewürm.",
    intro: "Der Boden gluckert verdächtig.\nVorsicht vor Gift!",
    partySize: 4,
    heights: [
      "0000000000",
      "0000000000",
      "0000000000",
      "0011001100",
      "0000000000",
      "0000000000",
      "0011001100",
      "0000000000",
      "0000000000",
    ],
    terrain: [
      "tggggggggt",
      "gwwggggwwg",
      "gwwggggwwg",
      "gggggggggg",
      "ggggwwgggg",
      "gguGwwGugg",
      "gggggggggg",
      "gwwggggwwg",
      "tggggggggt",
    ],
    spawns: [[0,4],[1,3],[1,5],[2,4],[0,3]],
    enemies: [
      { sp: "rettan",  lvl: 3, x: 8, y: 4 },
      { sp: "sleima",  lvl: 3, x: 7, y: 3 },
      { sp: "zubat",   lvl: 3, x: 8, y: 6 },
      { sp: "smettbo", lvl: 3, x: 7, y: 5 },
    ],
  },
  {
    id: 9, name: "Geröllhang", icon: "🪨", ambient: "canyon",
    desc: "Ein steiler Hang – die Gegner thronen oben.",
    intro: "Steine poltern den Hang herab.\nErklimm die Anhöhe!",
    partySize: 4,
    heights: [
      "4433221100",
      "4433221100",
      "3322110000",
      "3322110000",
      "2211000000",
      "2211000000",
      "1100000000",
      "1100000000",
      "0000000000",
    ],
    terrain: [
      "sssssddddd",
      "sssssddddd",
      "ssssddrddd",
      "ssssdddddd",
      "ssdddddddd",
      "ssdrdddddd",
      "sddddddddd",
      "sddddddddd",
      "dddddddddd",
    ],
    spawns: [[8,8],[9,7],[7,8],[8,7],[9,8]],
    enemies: [
      { sp: "kleinstein", lvl: 4, x: 1, y: 1 },
      { sp: "sandan",     lvl: 4, x: 3, y: 2 },
      { sp: "tragosso",   lvl: 4, x: 2, y: 3 },
      { sp: "menki",      lvl: 4, x: 4, y: 4 },
      { sp: "kleinstein", lvl: 5, x: 0, y: 0, boss: true },
    ],
  },
  {
    id: 10, name: "Nebelfriedhof", icon: "🪦", ambient: "ghost",
    desc: "Kristallgräber im wabernden Nebel.",
    intro: "Zwischen den Gräbern flüstert es …\nGeister lieben Flanken!",
    partySize: 5,
    heights: [
      "000000000",
      "000000000",
      "000000000",
      "000000000",
      "000111000",
      "000000000",
      "000000000",
      "000000000",
      "000000000",
    ],
    terrain: [
      "ppppppppp",
      "pPpppppPp",
      "pcpppppcp",
      "ppppppppp",
      "pppPPPppp",
      "ppcpppcpp",
      "ppppppppp",
      "ppppppppp",
      "pPpppppPp",
    ],
    spawns: [[3,8],[5,8],[4,8],[2,8],[6,8]],
    enemies: [
      { sp: "nebulak", lvl: 5, x: 2, y: 2 },
      { sp: "nebulak", lvl: 5, x: 5, y: 2 },
      { sp: "zubat",   lvl: 5, x: 7, y: 1 },
      { sp: "sleima",  lvl: 4, x: 4, y: 2 },
      { sp: "alpollo", lvl: 5, x: 4, y: 4, boss: true },
    ],
  },
  {
    id: 11, name: "Windklippen", icon: "🌬", ambient: "storm",
    desc: "Zwei Grate im Sturm – Flieger im Vorteil.",
    intro: "Der Wind heult über die Klippen.\nEtwas Großes kreist dort oben …",
    partySize: 5,
    heights: [
      "1233332100",
      "1233332100",
      "0122221000",
      "0011110000",
      "0000000000",
      "0011110000",
      "0122221000",
      "1233332100",
      "1233332100",
    ],
    terrain: [
      "ssssssssdd",
      "ssssssssdd",
      "dssssssddd",
      "ddssssdddd",
      "ddddddddrd",
      "ddssssdddd",
      "dssssssddd",
      "ssssssssdd",
      "ssssssssdd",
    ],
    spawns: [[9,4],[8,3],[8,5],[9,3],[9,5]],
    enemies: [
      { sp: "habitak",   lvl: 5, x: 2, y: 0 },
      { sp: "golbat",    lvl: 5, x: 3, y: 8 },
      { sp: "magnetilo", lvl: 6, x: 4, y: 1 },
      { sp: "garados",   lvl: 6, x: 1, y: 4, boss: true },
    ],
  },
  {
    id: 12, name: "Banditenlager", icon: "🏴", ambient: "arena",
    desc: "Ein Lager voller abgebrühter Schurken-Pokémon.",
    intro: "»Falsche Wiese, Freundchen.«\nDie Bande greift geschlossen an!",
    partySize: 5,
    heights: [
      "000000000",
      "000000000",
      "000000000",
      "001111100",
      "001111100",
      "001111100",
      "000000000",
      "000000000",
      "000000000",
    ],
    terrain: [
      "tgggggggt",
      "ggggggggg",
      "ggdddddgg",
      "ggdddddgg",
      "ggddbddgg",
      "ggdddddgg",
      "ggdddddgg",
      "ggggggggg",
      "tgggggggt",
    ],
    spawns: [[3,8],[5,8],[4,8],[2,8],[6,8]],
    enemies: [
      { sp: "rasaff",     lvl: 8, x: 4, y: 2, boss: true },
      { sp: "ultrigaria", lvl: 8, x: 3, y: 3 },
      { sp: "lektrobal",  lvl: 8, x: 5, y: 3 },
      { sp: "golbat",     lvl: 8, x: 6, y: 4 },
    ],
  },
];

/* Pro Etappe ein Karten-Pool; pro Run wird je eine Karte gewürfelt */
const STAGE_POOLS = [[0, 7], [1, 8], [2, 9], [3, 10], [4, 11], [5, 12], [6]];

/* ---------- Mana ----------
   Attacken kosten Mana statt PP. Start knapp, +MANA_REGEN je eigener Runde. */
const MANA_START = 1;
const MANA_REGEN = 2;
const MANA_MAX = 8;
function manaCost(m) {
  if (m.pp === Infinity) return 0;            // Hieb ist gratis
  let c;
  if (m.cat === "s") c = m.heal ? 4 : 3;      // Heilung/Status
  else c = m.pow <= 45 ? 2 : m.pow <= 60 ? 3 : m.pow <= 78 ? 4 : 5;
  if (m.aoe) c += 1;                          // Flächenattacken kosten extra
  return Math.min(6, c);
}

/* ---------- Roguelike-Run-Konstanten ---------- */
/* Ab diesem Level wird die Entwicklung angeboten (Reset auf Lv.1!) */
const EVO_LEVEL = 5;
/* Pool für Starter, Gefährten und Rekruten */
const PLAYER_POOL = ["pikachu","glumanda","schiggy","bisasam","evoli","machollo","abra","nebulak","kleinstein",
                     "fukano","menki","knofensa","sterndu","voltobal","sleima","karpador",
                     "vulpix","enton","quapsel","ponita","flegmon","krabby","owei","mauzi","digda","dratini","sichlor"];
const RECRUIT_POOL = [...PLAYER_POOL, "relaxo", "tragosso",
                     "elektek","magmar","rossana","lapras","aquana","blitza","flamara","chaneira","tauros",
                     "kicklee","nockchan","pinsir","arktos","zapdos","lavados"];
/* ---------- Relikte: passive Run-Items ---------- */
const RELICS = {
  wundsalbe:    { icon: "🧴", name: "Wundsalbe",     desc: "Nach jedem Sieg heilt der Trupp 10 % zusätzlich." },
  manakristall: { icon: "🔷", name: "Mana-Kristall", desc: "Alle Pokémon starten Kämpfe mit +1 Mana." },
  sprungfedern: { icon: "🦘", name: "Sprungfedern",  desc: "+1 Sprunghöhe für das ganze Team." },
  gluecksmuenze:{ icon: "🍀", name: "Glücksmünze",   desc: "+40 % Münzen aus Siegen." },
  epanhaenger:  { icon: "📿", name: "EP-Anhänger",   desc: "+20 % Erfahrungspunkte." },
  dornenpanzer: { icon: "🌵", name: "Dornenpanzer",  desc: "Nahkampf-Angreifer erleiden 3 Schaden." },
  schutzamulett:{ icon: "🛡", name: "Schutzamulett", desc: "Blocken reduziert 40 % statt 25 % Schaden." },
  phoenixfeder: { icon: "🪶", name: "Phönixfeder",   desc: "Einmal pro Run kehrt ein Gefallener sofort mit 30 % KP zurück." },
  klauen:       { icon: "🗡", name: "Scharfe Klauen",desc: "+10 % Volltreffer-Chance für dein Team." },
  tempoband:    { icon: "💨", name: "Tempo-Band",    desc: "+1 Tempo für das ganze Team." },
};

/* EP pro Etappe (Sieg); Ersatzbank erhält die Hälfte */
const STAGE_EXP = [110, 140, 170, 200, 230, 260, 300];
const EXP_PER_LEVEL = 100;
const SAVE_KEY = "poketactics_save_v2";
